<script lang="ts">
 import { useQuery,useConvexClient } from 'convex-svelte';
 import { api } from '$convex/_generated/api';
 import type { Doc } from '$convex/_generated/dataModel';
 import { states } from '$lib/data/nigeria';
 import TutorBundles from './TutorBundles.svelte';
 let {tickets=[],reports=[],payouts=[],events=[]}:{tickets?:Doc<'supportTickets'>[];reports?:Doc<'reports'>[];payouts?:Doc<'payouts'>[];events?:Doc<'ecosystemEvents'>[]}=$props();
 const client=useConvexClient(),health=useQuery(api.admin.health,{});
 let busy=$state(false),error=$state(''),notice=$state(''),notes=$state<Record<string,string>>({});
 let institutionName=$state(''),slug=$state(''),institutionState=$state(''),adminEmail=$state(''),seats=$state(30);
 async function institution(event:SubmitEvent){event.preventDefault();busy=true;error='';try{const id=await client.mutation(api.admin.createInstitution,{name:institutionName,slug,state:institutionState,adminEmail,seats});notice=`Institution trial created. Workspace: /inst/${id}`;}catch(e){error=e instanceof Error?e.message:'Institution setup failed.';}finally{busy=false;}}
 async function decide(kind:'support'|'report',id:string,expectedStatus:string,status:'under_review'|'resolved'|'open'){
 busy=true;error='';notice='';try{await client.mutation(api.admin.queueDecision,{kind,id,status,expectedStatus,note:notes[id]??''});notice='Status saved and audit recorded.';}catch(e){error=e instanceof Error?e.message:'Unable to save decision.';}finally{busy=false;}}
 async function approve(payoutId:Doc<'payouts'>['_id']){busy=true;error='';try{await client.mutation(api.money.approvePayout,{payoutId});notice='Your independent payout approval was recorded.';}catch(e){error=e instanceof Error?e.message:'Approval failed.';}finally{busy=false;}}
 async function probe(){busy=true;error='';notice='';try{const result=await client.action(api.ai.generate,{exam:'JAMB',subject:'Physics',count:1});notice=`Live AI request completed using ${result.model}. ${result.stored} validated draft saved for independent review.`;}catch(e){error=e instanceof Error?e.message:'Live AI check failed.';}finally{busy=false;}}
</script>
<div class="grid gap-5 mb-5">
 <section class="panel p-5"><h2 class="text-xl font-semibold">Live AI verification</h2><p class="text-sm muted mt-2">Generate one original practice draft with the live provider. Validated content stays unreviewed until independent approval. The result is retained in the protected health report.</p><button class="ctl mt-3" disabled={busy} onclick={probe}>Run live AI check (1 draft)</button><a class="ctl mt-3 ml-2" href="/tutor-bundle">Manage tutor bundles</a></section>
 <form class="panel p-5 grid sm:grid-cols-2 gap-3" onsubmit={institution}><h2 class="text-xl font-semibold sm:col-span-2">Onboard an institution</h2><p class="text-sm muted sm:col-span-2">Create a 30-day trial and assign a verified adult institution administrator.</p><label class="label">Institution name<input class="field mt-2" bind:value={institutionName} required minlength="3" maxlength="150"/></label><label class="label">Unique slug<input class="field mt-2" bind:value={slug} required pattern={'[a-z0-9-]{3,50}'}/></label><label class="label">State<select class="field mt-2" bind:value={institutionState} required><option value="">Select state</option>{#each states as state}<option value={state}>{state}</option>{/each}</select></label><label class="label">Administrator email<input class="field mt-2" type="email" bind:value={adminEmail} required/></label><label class="label">Trial seats<input class="field mt-2" type="number" min="1" max="1000" bind:value={seats} required/></label><button class="ctl ctl-primary self-end" disabled={busy}>Create institution trial</button></form>
 {#if error}<p class="panel-sunk p-4" role="alert">{error}</p>{/if}{#if notice}<p class="panel-sunk p-4" role="status">{notice}</p>{/if}
 <section class="panel p-5"><div class="flex flex-wrap justify-between gap-3"><h2 class="text-xl font-semibold">Configuration health</h2><a href="/api/admin/health" class="link" target="_blank" rel="noopener">View protected health endpoint</a></div><p class="muted text-sm mt-2">Configuration checks do not send emails, charge cards or consume AI credits.</p>{#if health.data}<div class="grid sm:grid-cols-2 lg:grid-cols-3 gap-3 mt-4">{#each Object.entries(health.data).filter(([key])=>key!=='checkedAt') as [key,value]}{@const check=value as {status:string;detail:string;fallbackConfigured?:boolean}}<article class="panel-sunk p-4 min-w-0"><div class="flex justify-between gap-2"><h3 class="capitalize font-semibold">{key}</h3><span class="badge">{check.status.replaceAll('_',' ')}</span></div><p class="text-sm muted mt-2">{check.detail}</p>{#if key==='ai'}<p class="text-xs muted mt-2">Workers AI fallback: {check.fallbackConfigured?'configured':'missing'}</p>{/if}</article>{/each}</div><p class="text-xs muted mt-3">Checked {new Date(health.data.checkedAt).toLocaleString()}</p>{:else if health.error}<p role="alert">Unable to load health: {health.error.message}</p>{:else}<p role="status" class="mt-3">Checking configuration…</p>{/if}</section>
 {#each [{kind:'support' as const,title:'Support requests',rows:tickets},{kind:'report' as const,title:'Safety reports',rows:reports}] as queue}<section class="panel p-5"><h2 class="text-xl font-semibold">{queue.title}</h2><div class="grid gap-3 mt-4">{#each queue.rows as row}<article class="panel-sunk p-4"><div class="flex flex-wrap justify-between gap-2"><h3 class="font-semibold">{'subject' in row?row.subject:row.involvesMinor?'Priority: learner safeguarding':'Safety report'}</h3><span class="badge">{row.status.replaceAll('_',' ')}</span></div><p class="text-sm whitespace-pre-wrap break-words mt-3">{row.body}</p><label class="label mt-3" for={`decision-${row._id}`}>Decision rationale</label><textarea id={`decision-${row._id}`} class="field mt-2" bind:value={notes[row._id]} maxlength="1000" placeholder="Record your review and the next action."></textarea><div class="flex flex-wrap gap-2 mt-3">{#each ['under_review','resolved','open'] as status}<button class="ctl ctl-sm" disabled={busy||row.status===status||(notes[row._id]??'').trim().length<10} onclick={()=>decide(queue.kind,row._id,row.status,status as 'under_review'|'resolved'|'open')}>{status==='open'?'Reopen':status==='resolved'?'Resolve':'Start review'}</button>{/each}</div></article>{:else}<p class="muted">No requests in this queue.</p>{/each}</div></section>{/each}
 <section class="panel p-5"><h2 class="text-xl font-semibold">Payout approval queue</h2><p class="text-sm muted mt-2">Two different staff reviewers are required. Providers remain disabled until payment acceptance is complete.</p><div class="grid gap-3 mt-4">{#each payouts as payout}<article class="panel-sunk p-4"><p class="font-semibold">{new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN'}).format(Number(payout.amount)/100)}</p><p class="text-sm muted mt-2">{payout.status.replaceAll('_',' ')} · {payout.approvals.length}/2 approvals</p>{#if payout.status==='awaiting_approval'}<button class="ctl mt-3" disabled={busy} onclick={()=>approve(payout._id)}>Record independent approval</button>{/if}</article>{:else}<p class="muted">No payout requests.</p>{/each}</div></section>
 <section class="panel p-5"><h2 class="text-xl font-semibold">E-WIN event delivery</h2><p class="text-sm muted mt-2">Events await a signed central receipt. Delivery records do not create wallet credits.</p><div class="grid gap-2 mt-4">{#each events as event}<div class="panel-sunk p-3 flex flex-wrap justify-between gap-3"><span class="text-sm break-all">{event.type} · {event.subject}</span><span class="badge">{event.deliveredAt?'Acknowledged':'Awaiting central receipt'}</span></div>{:else}<p class="muted">No queued ecosystem events.</p>{/each}</div></section>
</div>
<TutorBundles/>
