<script lang="ts">
 import { useConvexClient } from 'convex-svelte';
 import { api } from '$convex/_generated/api';
 import type { Doc } from '$convex/_generated/dataModel';
 let { questions=[], verifications=[], users=[] }: { questions?:Doc<'questions'>[];verifications?:Doc<'verifications'>[];users?:Doc<'users'>[] }=$props();
 const client=useConvexClient();let busy=$state(false),error=$state(''),notice=$state(''),evidence=$state('');
 let name=$state(''),role=$state(''),quote=$state(''),example=$state(true),consent=$state(false);
 let appointmentNote=$state('');
 async function run(work:()=>Promise<unknown>){busy=true;error='';notice='';try{await work();notice='Decision saved to the audit log.';}catch(e){error=e instanceof Error?e.message:'Unable to save decision.';}finally{busy=false;}}
</script>
<div class="grid gap-5">
 <label class="label">Staff appointment rationale<input class="field mt-2" bind:value={appointmentNote} minlength="10" maxlength="1000" placeholder="Only the nominated owner can appoint an independent administrator."/></label>
 {#if error}<p role="alert" class="panel-sunk p-4" style="color:var(--bad)">{error}</p>{/if}{#if notice}<p role="status" class="panel-sunk p-4">{notice}</p>{/if}
 <section class="panel p-5"><h2 class="text-xl font-semibold">AI and editorial drafts</h2><p class="muted text-sm mt-2">Check accuracy, clarity, answer keys and originality before publishing. Drafts are excluded from learner practice.</p><div class="grid gap-3 mt-4">{#each questions as q}<article class="panel-sunk p-4"><p class="eyebrow">{q.exam} · {q.subject} · {q.topic}</p><h3 class="font-semibold mt-3">{q.stem}</h3><ol class="list-[upper-alpha] ml-5 mt-3 text-sm">{#each q.options as option,i}<li class="py-1">{option}{i===q.answer?' ✓':''}</li>{/each}</ol><p class="muted text-sm mt-3">{q.explanation}</p><div class="flex gap-2 mt-4"><button class="ctl ctl-primary" disabled={busy} onclick={()=>run(()=>client.mutation(api.admin.reviewQuestion,{id:q._id,approve:true}))}>Approve and publish</button><button class="ctl" disabled={busy} onclick={()=>run(()=>client.mutation(api.admin.reviewQuestion,{id:q._id,approve:false}))}>Retire draft</button></div></article>{:else}<p class="muted">No drafts await review.</p>{/each}</div></section>
 <section class="panel p-5"><h2 class="text-xl font-semibold">Identity and safeguarding</h2><label class="label mt-4" for="verification-evidence">Evidence reviewed and decision rationale</label><textarea id="verification-evidence" class="field mt-2" bind:value={evidence} minlength="10" maxlength="1000" placeholder="Record the provider reference and the evidence supporting your decision."></textarea><div class="grid gap-3 mt-4">{#each verifications.filter(x=>['pending','under_review'].includes(x.status)) as item}<article class="panel-sunk p-4"><p class="font-semibold">{item.kind} · {item.userId}</p><p class="muted text-sm mt-2">{item.provider??'Manual review'} · {item.providerRef??'Evidence needed'}</p><div class="flex gap-2 mt-3">{#if item.status==='pending'}<button class="ctl" disabled={busy} onclick={()=>run(()=>client.mutation(api.admin.startVerification,{id:item._id}))}>Start review</button>{/if}<button class="ctl ctl-primary" disabled={busy||evidence.trim().length<10} onclick={()=>run(()=>client.mutation(api.admin.reviewVerification,{id:item._id,approve:true,note:evidence}))}>Approve evidence</button><button class="ctl" disabled={busy||evidence.trim().length<10} onclick={()=>run(()=>client.mutation(api.admin.reviewVerification,{id:item._id,approve:false,note:evidence}))}>Reject</button></div></article>{:else}<p class="muted">No pending verification requests.</p>{/each}</div></section>
 <section class="panel p-5"><h2 class="text-xl font-semibold">Account access</h2><div class="grid gap-3 mt-4">{#each users as user}<article class="panel-sunk p-3 flex flex-wrap justify-between gap-3"><div><p class="font-semibold">{user.name}</p><p class="muted text-xs">{user.status} · {user.isMinor?'Under 18':'Adult'}</p></div><div class="flex gap-2"><button class="ctl ctl-sm" disabled={busy} onclick={()=>run(()=>client.mutation(api.admin.accountStatus,{id:user._id,status:user.status==='active'?'paused':'active'}))}>{user.status==='active'?'Pause access':'Restore access'}</button>{#if !user.isMinor&&user.status==='active'}<button class="ctl ctl-sm" disabled={busy||appointmentNote.trim().length<10} onclick={()=>run(()=>client.mutation(api.admin.grantStaff,{userId:user._id,note:appointmentNote}))}>Appoint staff</button>{/if}</div></article>{/each}</div></section>
 <form class="panel p-5 grid gap-3" onsubmit={event=>{event.preventDefault();run(()=>client.mutation(api.admin.testimonial,{name,role,quote,example,hasConsent:consent}));}}><h2 class="text-xl font-semibold">Publish a community story</h2><label class="label" for="story-name">Name or example persona</label><input id="story-name" class="field" bind:value={name} required maxlength="100"/><label class="label" for="story-role">Role</label><input id="story-role" class="field" bind:value={role} required maxlength="100"/><label class="label" for="story-quote">Statement</label><textarea id="story-quote" class="field" bind:value={quote} required minlength="20" maxlength="1500"></textarea><label class="flex gap-3 text-sm"><input type="checkbox" bind:checked={example}/>Clearly label as an example story</label><label class="flex gap-3 text-sm"><input type="checkbox" bind:checked={consent} required/>I confirm permission to publish this statement, or that this is a fictional example.</label><button class="ctl ctl-primary" disabled={busy}>Publish story</button></form>
</div>
