<script lang="ts">
 import { onMount } from 'svelte';
 import type { Doc } from '$convex/_generated/dataModel';
 let {attempts=[]}:{attempts?:Doc<'attempts'>[]}=$props();
 let frame=$state<HTMLIFrameElement>(),open=$state(false),connected=$state(false),busy=$state(false),error=$state(''),notice=$state(''),centralCode=$state(''),consent=$state(false);
 const origin='https://ewinproject.org';const requests=new Map<string,{resolve:(value:any)=>void;reject:(reason:Error)=>void;timer:ReturnType<typeof setTimeout>}>();
 function request(method:string,args?:unknown){return new Promise<any>((resolve,reject)=>{if(!frame?.contentWindow)return reject(new Error('Open the connection panel first.'));const id=crypto.randomUUID();const timer=setTimeout(()=>{requests.delete(id);reject(new Error('E-WIN did not respond. Sign in there and reconnect.'));},15000);requests.set(id,{resolve,reject,timer});frame.contentWindow.postMessage({type:'ewin:request',id,method,args},origin);});}
 onMount(()=>{const receive=(event:MessageEvent)=>{if(event.origin!==origin||event.source!==frame?.contentWindow)return;const data=event.data;if(data?.type==='ewin:ready')connected=data.authenticated===true;if(data?.type!=='ewin:response'||typeof data.id!=='string')return;const pending=requests.get(data.id);if(!pending)return;clearTimeout(pending.timer);requests.delete(data.id);data.error?pending.reject(new Error(data.error)):pending.resolve(data.result);};window.addEventListener('message',receive);return()=>{window.removeEventListener('message',receive);for(const pending of requests.values()){clearTimeout(pending.timer);pending.reject(new Error('Connection closed.'));}requests.clear();};});
 async function snapshot(){busy=true;error='';try{const result=await request('snapshot');centralCode=result.member?.referralCode??'';notice='Central account connected. Your E-WIN referral code works across its registered platforms.';}catch(e){error=e instanceof Error?e.message:'Connection failed.';}finally{busy=false;}}
 async function sync(attempt:Doc<'attempts'>){busy=true;error='';try{if(!consent)throw new Error('Confirm sharing your selected learning result.');await request('syncRecord',{sourceId:`schoolxense:attempt:${attempt._id}`,title:`SchoolXense ${attempt.exam} · ${attempt.subject}`,data:{version:1,exam:attempt.exam,subject:attempt.subject,pct:attempt.pct,grade:attempt.grade,completedAt:attempt.endedAt}});notice='Learning result copied to your private central E-WIN record.';}catch(e){error=e instanceof Error?e.message:'Unable to sync result.';}finally{busy=false;}}
</script>
<section class="panel p-5 mb-5 min-w-0"><h2 class="text-xl font-semibold">Connect your E-WIN account</h2><p class="muted text-sm mt-2">Use the mother platform’s referral code and optionally copy completed learning results to your private central record. SchoolXense settles its own orders; central reports do not credit the E-WIN wallet.</p><button class="ctl mt-4" onclick={()=>open=!open}>{open?'Close connection panel':'Open secure E-WIN connection'}</button>{#if open}<iframe bind:this={frame} src={`https://ewinproject.org/connect/schoolcbt?origin=${encodeURIComponent(location.origin)}`} title="Secure E-WIN account connection" class="w-full h-[32rem] mt-4 rounded-xl border-0" referrerpolicy="strict-origin-when-cross-origin"></iframe><p class="text-xs muted mt-2">Sign in to E-WIN inside its own origin, then reconnect. Account sessions stay with their respective applications.</p><button class="ctl mt-3" disabled={busy||!connected} onclick={snapshot}>Read my central referral code</button>{/if}
{#if error}<p class="mt-3 text-sm" role="alert">{error}</p>{/if}{#if notice}<p class="mt-3 text-sm" role="status">{notice}</p>{/if}
{#if centralCode}<p class="mt-4">E-WIN code: <strong>{centralCode}</strong></p><a class="link break-all block text-sm mt-2" href={`https://schoolxense.ewinproject.org/signup?ref=${centralCode}`}>https://schoolxense.ewinproject.org/signup?ref={centralCode}</a><a class="link block text-sm mt-2" href={`https://ewinproject.org/go/schoolcbt?ref=${centralCode}`} target="_blank" rel="noopener">Open an E-WIN platform invite</a>{/if}
{#if connected}<label class="flex gap-3 text-sm mt-4"><input type="checkbox" bind:checked={consent}/>I agree to copy the selected learning result to my signed-in central E-WIN account.</label><div class="grid gap-2 mt-3">{#each attempts.filter(x=>x.endedAt) as attempt}<div class="panel-sunk p-3 flex flex-wrap justify-between gap-3"><span>{attempt.exam.toUpperCase()} · {attempt.subject} · {attempt.pct}%</span><button class="ctl ctl-sm" disabled={busy||!consent} onclick={()=>sync(attempt)}>Sync learning result</button></div>{:else}<p class="muted text-sm">Complete a practice session to share a result.</p>{/each}</div>{/if}</section>
