<script lang="ts">
 import {useQuery,useConvexClient} from 'convex-svelte';import {api} from '$convex/_generated/api';import type {Id,Doc} from '$convex/_generated/dataModel';
 let {tenantId,exams=[]}:{tenantId:Id<'tenants'>;exams?:Doc<'hostedExams'>[]}=$props();
 const client=useConvexClient();let busy=$state(false),error=$state(''),notice=$state(''),learner=$state(''),className=$state(''),title=$state(''),exam=$state('jamb'),subject=$state('physics'),date=$state(''),seats=$state(30),minutes=$state(60),selected=$state<string[]>([]);
 const questions=useQuery(api.institutions.reviewedQuestions,()=>({tenantId,exam,subject}));
 async function run(work:()=>Promise<unknown>){busy=true;error='';notice='';try{await work();notice='Institution action saved.';}catch(e){error=e instanceof Error?e.message:'Unable to save.';}finally{busy=false;}}
</script>
<div class="grid gap-4 mb-5">
{#if error}<p role="alert" class="panel-sunk p-4">{error}</p>{/if}{#if notice}<p role="status" class="panel-sunk p-4">{notice}</p>{/if}
<form class="panel p-5 grid gap-3" onsubmit={event=>{event.preventDefault();run(()=>client.mutation(api.institutions.assignSeat,{tenantId,userId:learner as Id<'users'>,className}));}}><h2 class="font-semibold">Assign a licensed learner seat</h2><label class="label">Learner account ID<input class="field mt-2" bind:value={learner} required/></label><label class="label">Class<input class="field mt-2" bind:value={className} maxlength="100"/></label><p class="muted text-sm">The learner must have a verified account. Seat limits and licence expiry are checked on the server.</p><button class="ctl" disabled={busy}>Assign seat</button></form>
<form class="panel p-5 grid sm:grid-cols-2 gap-3" onsubmit={event=>{event.preventDefault();run(()=>client.mutation(api.institutions.scheduleExam,{tenantId,title,exam,subject,date:new Date(date).getTime(),seats,durationMin:minutes,questionIds:selected as Id<'questions'>[]}));}}><h2 class="font-semibold sm:col-span-2">Schedule a reviewed assessment</h2><label class="label">Title<input class="field mt-2" bind:value={title} required maxlength="200"/></label><label class="label">Exam<input class="field mt-2" bind:value={exam} onchange={()=>selected=[]} required/></label><label class="label">Subject<input class="field mt-2" bind:value={subject} onchange={()=>selected=[]} required/></label><label class="label">Start time<input class="field mt-2" type="datetime-local" bind:value={date} required/></label><label class="label">Seats<input class="field mt-2" type="number" min="1" max="1000" bind:value={seats} required/></label><label class="label">Duration (minutes)<input class="field mt-2" type="number" min="5" max="240" bind:value={minutes} required/></label><fieldset class="sm:col-span-2 grid gap-2"><legend class="label mb-2">Reviewed questions</legend>{#each questions.data??[] as question}<label class="panel-sunk p-3 flex gap-3 text-sm"><input type="checkbox" bind:group={selected} value={question._id}/>{question.stem}</label>{:else}<p class="muted text-sm">No reviewed questions match this exam and subject. Editorial approval is required first.</p>{/each}</fieldset><p class="text-sm muted sm:col-span-2">Scheduling creates a server-priced institutional invoice. An invoice is not proof of payment.</p><button class="ctl ctl-primary sm:col-span-2" disabled={busy||!selected.length}>Schedule assessment</button></form>
<section class="panel p-5"><h2 class="font-semibold">Assessment lifecycle</h2><div class="grid gap-3 mt-3">{#each exams as item}<article class="panel-sunk p-3"><p class="font-semibold">{item.title} · {item.status}</p><p class="muted text-sm mt-2">{new Date(item.date).toLocaleString()}</p><div class="flex gap-2 mt-3">{#if item.status==='scheduled'}<button class="ctl ctl-sm" disabled={busy||item.date>Date.now()} onclick={()=>run(()=>client.mutation(api.institutions.examStatus,{tenantId,id:item._id,status:'live'}))}>Start live assessment</button>{/if}{#if item.status==='live'}<button class="ctl ctl-sm" disabled={busy} onclick={()=>run(()=>client.mutation(api.institutions.examStatus,{tenantId,id:item._id,status:'closed'}))}>Close assessment</button>{/if}</div></article>{:else}<p class="muted text-sm">No assessments scheduled.</p>{/each}</div></section>
</div>
