<script lang="ts">
	import { page } from '$app/state';
	import { goto } from '$app/navigation';
	import { useAuth } from '@mmailaender/convex-better-auth-svelte/svelte';
	import { useQuery, useConvexClient } from 'convex-svelte';
	import { api } from '$convex/_generated/api';
	import type { Id } from '$convex/_generated/dataModel';
	import { naira } from '$ui/format';
	import { APP_URL } from '$lib/config';
	import Icon from '$ui/Icon.svelte';
	import LivePractice from './LivePractice.svelte';
	import LiveCheckout from './LiveCheckout.svelte';
	import AdminReview from './AdminReview.svelte';
 import AdminOperations from './AdminOperations.svelte';
 import ResidenceFields from './ResidenceFields.svelte';
 import EwinConnection from './EwinConnection.svelte';
 import InstitutionActions from './InstitutionActions.svelte';
 let residenceState=$state(''),lga=$state(''),whatsapp=$state(''),nin=$state('');
 let loadedProfile=$state(false);
 let supportSubject=$state(''),supportBody=$state('');
 $effect(()=>{if(profile.data&&!loadedProfile){loadedProfile=true;residenceState=profile.data.state??'';lga=profile.data.lga??'';whatsapp=profile.data.whatsapp??'';name=profile.data.name;headline=profile.data.headline??'';}});
	const client = useConvexClient(), auth = useAuth();
	const domain = $derived(page.url.pathname.split('/')[1] || 'home');
	const detail = $derived(page.url.pathname.split('/')[2]);
	const profile = useQuery(api.portal.profile, () => auth.isAuthenticated ? {} : 'skip');
	const workspace = useQuery(api.portal.workspace, () => profile.data && (domain !== 'ops' || profile.data.roles.includes('staff')) ? { domain, ...(domain === 'inst' && detail ? { tenantId: detail as Id<'tenants'> } : {}) } : 'skip');
	const offers = useQuery(api.portal.offers, () => ['book', 'offers', 'home'].includes(domain) ? {} : 'skip');
	const messages = useQuery(api.collab.threadMessages, () => domain === 'threads' && detail ? { threadId: detail as Id<'threads'> } : 'skip');
	const titles: Record<string, string> = { home: 'Your learning overview', practice: 'Make progress, one question at a time', review: 'Your review queue', plan: 'Your study plan', wallet: 'Your wallet', earn: 'Your earning workspace', payouts: 'Payout requests', book: 'Find the right tutor', sessions: 'Your tutoring sessions', requests: 'Incoming session requests', offers: 'Your teaching offers', studio: 'Question Studio', packs: 'Your study packs', teams: 'Your collaboration teams', contracts: 'Contracts and opportunities', tasks: 'Your task board', threads: 'Your conversations', family: 'Your family workspace', certificates: 'Your achievements', record: 'Your learning record', notifications: 'Your notifications', settings: 'Account and privacy', referrals: 'Invite your community', ops: 'Administration', inst: 'Institution workspace', checkout: 'Complete your order', attempt: 'Your practice results', skills: 'Your skills journey' };
	const title = $derived(titles[domain] ?? 'Your workspace');
	let busy = $state(false), error = $state(''), notice = $state('');
	let name = $state(''), headline = $state(''), message = $state(''), subject = $state('physics'), price = $state(1500), slot = $state(''), selectedOffer = $state('');
	let selectedBrief = $state(''), questionStem = $state(''), optionText = $state(''), correctAnswer = $state(0), explanation = $state('');
	let teamName = $state(''), blurb = $state(''), uploadKind = $state<'image' | 'document'>('document');
	let activated = $state(false);
	let guardianCode=$state(''),guardianAck=$state(false),inviteCode=$state('');
	type Row = Record<string, any>;
	const data = $derived((workspace.data ?? {}) as Record<string, any>);
	function rows(key: string): Row[] { return Array.isArray(data[key]) ? data[key] : []; }
	function display(row: Row) { return row.title || row.name || row.subject || row.topic || row.action || row.planId || row.scope || row.exam || 'Record'; }
	async function run(work: () => Promise<unknown>, success = 'Saved successfully.') {
		busy = true; error = ''; notice = '';
		try { await work(); notice = success; }
		catch (e) { error = e instanceof Error ? e.message : 'Unable to save. Please try again.'; }
		finally { busy = false; }
	}
	$effect(() => { if (domain === 'ops' && page.url.searchParams.get('activate') === '1' && profile.data && !activated) { activated = true; run(() => client.mutation(api.portal.activateOwner, {}), 'Administrator access activated.'); } });
	async function book(event: SubmitEvent) { event.preventDefault(); await run(async () => { const bookingId = await client.mutation(api.market.create, { offerId: selectedOffer as Id<'offers'>, topic: subject, slot, minutes: 45, note: message }); await goto('/sessions'); return bookingId; }, 'Booking saved. Complete payment from your sessions.'); }
	async function payBooking(bookingId: Id<'bookings'>) { await run(async () => { const paymentId = await client.mutation(api.checkout.order, { kind: 'booking', refId: bookingId }); await goto(`/checkout/${paymentId}`); }); }
	async function send(event: SubmitEvent) { event.preventDefault(); await run(async () => { await client.mutation(api.collab.send, { threadId: detail as Id<'threads'>, body: message }); message = ''; }, 'Message sent.'); }
	async function saveProfile(event: SubmitEvent) { event.preventDefault(); await run(async () => {await client.mutation(api.users.upsertProfile, { name: name || profile.data?.name, headline,state:residenceState,lga,whatsapp });if(nin){await client.action(api.identity.update,{state:residenceState,lga,whatsapp,nin});nin='';}}); }
	async function publishOffer(event: SubmitEvent) { event.preventDefault(); await run(() => client.mutation(api.portal.createOffer, { title: headline, subject, priceKobo: Math.round(price * 100), availability: slot }), 'Offer published.'); }
	async function submitQuestion(event: SubmitEvent) { event.preventDefault(); await run(() => client.mutation(api.studio.submit, { briefId: selectedBrief as Id<'studioBriefs'>, stem: questionStem, options: optionText.split('\n').map(x => x.trim()).filter(Boolean), answer: correctAnswer, explanation }), 'Question submitted for review.'); }
	async function upload(event: Event) {
		const file = (event.target as HTMLInputElement).files?.[0]; if (!file) return;
		await run(async () => {
			const grantResponse = await fetch('/api/media/sign-upload', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ kind: uploadKind, contentType: file.type, size: file.size }) });
			const grant = await grantResponse.json(); if (!grantResponse.ok) throw new Error(grant.message || 'Upload permission denied.');
			const response = await fetch(grant.url, { method: 'PUT', headers: { 'Content-Type': file.type }, body: file });
			if (!response.ok) throw new Error('File upload failed.');
		}, 'File uploaded securely.');
	}
	async function exportData() { await run(async () => { const data = await client.query(api.users.exportMine, {}); const blob = new Blob([JSON.stringify(data, (_, x) => typeof x === 'bigint' ? x.toString() : x, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'schoolxense-account.json'; a.click(); URL.revokeObjectURL(url); }, 'Account export downloaded.'); }
</script>

<svelte:head><title>{title} · SchoolXense</title><meta name="robots" content="noindex,nofollow" /></svelte:head>
<div class="flex flex-wrap justify-between gap-4 items-end mb-6"><div><p class="eyebrow">SchoolXense workspace</p><h1 class="text-3xl font-semibold mt-2">{title}</h1><p class="muted mt-2">{domain === 'ops' ? 'Review the queues that need your attention.' : 'Your changes and progress are saved to your account.'}</p></div><span class="badge badge-good"><Icon name="signal" size={13} />Live updates</span></div>
{#if error}<p class="panel-sunk p-4 mb-4" role="alert" style="color:var(--bad)">{error}</p>{/if}
{#if notice}<p class="panel-sunk p-4 mb-4" role="status" style="color:var(--good)">{notice}</p>{/if}
{#if workspace.error}<div class="panel p-6"><h2 class="font-semibold">{String(workspace.error).includes('SUBSCRIPTION_REQUIRED')?'An active plan is required':'Unable to load this workspace'}</h2><p class="muted mt-2">{String(workspace.error).includes('SUBSCRIPTION_REQUIRED')?'Choose a plan that includes this feature. Your wallet funds and transaction history remain available.':'Check your connection and account permissions, then retry.'}</p>{#if String(workspace.error).includes('SUBSCRIPTION_REQUIRED')}<a href="/pricing" class="ctl ctl-primary mt-4">View plans and renew</a>{/if}</div>
{:else if domain === 'ops' && !profile.data?.roles.includes('staff')}<div class="panel p-6"><Icon name="lock" size={24} /><h2 class="font-semibold mt-3">Administrator access required</h2><p class="muted mt-2">Only the verified nominated owner can activate the admin console.</p><a href="/admin-login" class="ctl mt-4">Administrator sign in</a></div>
{:else if domain === 'practice'}
	{#key page.url.pathname}<LivePractice initialExam={detail || 'jamb'} initialSubject={page.url.pathname.split('/')[3] || 'physics'} />{/key}
{:else if domain === 'checkout' && detail}<LiveCheckout paymentId={detail as Id<'payments'>} />
{:else}
	{#if domain === 'home'}
		<div class="grid sm:grid-cols-3 gap-4 mb-5">{#each [['Practice sessions', rows('attempts').length, 'target'], ['Topics practised', rows('mastery').length, 'chart'], ['Review cards due', rows('review').length, 'refresh']] as [label, value, icon]}<div class="panel p-5"><Icon name={String(icon)} size={20} /><p class="muted mt-3 text-sm">{label}</p><p class="num text-3xl font-semibold mt-2">{value}</p></div>{/each}</div>
		<div class="panel p-6 mb-5 flex flex-wrap gap-4 items-center justify-between"><div><h2 class="text-xl font-semibold">Ready for your next session?</h2><p class="muted mt-2">Build mastery with reviewed questions and save your progress.</p></div><a href="/practice" class="ctl ctl-primary">Start practice<Icon name="play" size={16} /></a></div>
	{/if}
	{#if ['wallet', 'earn', 'payouts'].includes(domain)}
		<div class="panel p-6 mb-5"><p class="eyebrow">Available balance</p><p class="num text-4xl font-semibold mt-3">{naira(Number(data.balance ?? 0))}</p><p class="muted text-sm mt-3">Settled earnings only. Payouts require a verified, name-matched bank account.</p></div>
		{#if domain === 'payouts'}<form class="panel p-5 grid gap-3 mb-5" onsubmit={event => { event.preventDefault(); run(() => client.mutation(api.money.requestPayout, { amountKobo: BigInt(Math.round(price * 100)) })); }}><label class="label" for="payout-amount">Amount in naira</label><input id="payout-amount" class="field" type="number" min="2000" step="1" bind:value={price} required /><button class="ctl ctl-primary" disabled={busy}>Request payout</button></form>{/if}
	{/if}
	{#if domain === 'book'}
		<form class="panel p-5 grid sm:grid-cols-2 gap-4 mb-5" onsubmit={book}><div class="sm:col-span-2"><label class="label" for="book-offer">Choose a tutor offer</label><select id="book-offer" class="field" bind:value={selectedOffer} required><option value="">Select an available offer</option>{#each offers.data ?? [] as offer}<option value={offer._id}>{offer.title} · {naira(Number(offer.price))} / 45 min</option>{/each}</select></div><div><label class="label" for="book-topic">Topic</label><input id="book-topic" class="field" bind:value={subject} required maxlength="120" /></div><div><label class="label" for="book-slot">Preferred time</label><input id="book-slot" class="field" type="datetime-local" bind:value={slot} required /></div><div class="sm:col-span-2"><label class="label" for="book-note">What would you like help understanding?</label><textarea id="book-note" class="field" bind:value={message} maxlength="2000"></textarea></div><button class="ctl ctl-primary sm:col-span-2" disabled={busy || !offers.data?.length}>Request session</button></form>
		{#if offers.data?.length === 0}<p class="panel-sunk p-5 mb-5">No verified tutors have published offers yet. Check back soon or <a class="link" href="/#enquiries">send an enquiry</a>.</p>{/if}
	{/if}
	{#if domain === 'sessions' || domain === 'requests'}<div class="grid gap-3 mb-5">{#each rows('bookings') as booking}<section class="panel p-5"><div class="flex justify-between gap-3"><h2 class="font-semibold">{booking.topic}</h2><span class="badge">{booking.status.replaceAll('_', ' ')}</span></div><p class="muted text-sm mt-2">{booking.slot} · {booking.minutes} minutes · {naira(Number(booking.price))}</p><div class="flex flex-wrap gap-2 mt-4">{#if booking.status === 'pending_payment' && booking.learnerId === profile.data?._id}<button class="ctl ctl-primary" disabled={busy} onclick={() => payBooking(booking._id)}>Complete payment</button>{/if}{#if booking.threadId}<a class="ctl" href={`/threads/${booking.threadId}`}>Open conversation</a>{/if}{#if booking.tutorId === profile.data?._id && booking.status === 'confirmed'}<button class="ctl" disabled={busy} onclick={() => run(() => client.mutation(api.market.deliver, { bookingId: booking._id }))}>Mark delivered</button>{/if}{#if booking.learnerId === profile.data?._id && booking.status === 'delivered'}<button class="ctl" disabled={busy} onclick={() => run(() => client.mutation(api.market.confirm, { bookingId: booking._id, rating: 5, text: 'Delivery confirmed by learner.' }))}>Confirm delivery</button>{/if}</div></section>{:else}<div class="panel p-5 muted">Your booked sessions will appear here.</div>{/each}</div>{/if}
	{#if domain === 'offers'}<form class="panel p-5 grid gap-3 mb-5" onsubmit={publishOffer}><h2 class="font-semibold">Publish a teaching offer</h2><label class="label" for="offer-title">Title</label><input id="offer-title" class="field" bind:value={headline} required maxlength="200" /><label class="label" for="offer-subject">Subject</label><input id="offer-subject" class="field" bind:value={subject} required /><label class="label" for="offer-price">Price per 45 minutes (₦)</label><input id="offer-price" class="field" type="number" min="500" bind:value={price} required /><label class="label" for="offer-slot">Availability</label><input id="offer-slot" class="field" bind:value={slot} required /><button class="ctl ctl-primary" disabled={busy}>Publish verified offer</button></form>{/if}
	{#if domain === 'studio'}
		<form class="panel p-5 grid gap-3 mb-5" onsubmit={submitQuestion}><h2 class="font-semibold">Submit an original question</h2><label class="label" for="studio-brief">Open brief</label><select id="studio-brief" class="field" bind:value={selectedBrief} required><option value="">Select a brief</option>{#each rows('briefs') as brief}<option value={brief._id}>{brief.subject} · {brief.topic}</option>{/each}</select><label class="label" for="studio-stem">Question</label><textarea id="studio-stem" class="field" bind:value={questionStem} required></textarea><label class="label" for="studio-options">Four options, one per line</label><textarea id="studio-options" class="field" bind:value={optionText} required></textarea><label class="label" for="studio-answer">Correct option</label><select id="studio-answer" class="field" bind:value={correctAnswer}>{#each [0, 1, 2, 3] as n}<option value={n}>{String.fromCharCode(65 + n)}</option>{/each}</select><label class="label" for="studio-explanation">Explanation</label><textarea id="studio-explanation" class="field" bind:value={explanation} required></textarea><button class="ctl ctl-primary" disabled={busy}>Submit for review</button></form>
		<form class="panel p-5 grid gap-3 mb-5" onsubmit={event => { event.preventDefault(); run(async () => { const response = await fetch('/api/ai/generate', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ exam: 'jamb', subject, count: 5 }) }); const result = await response.json(); if (!response.ok) throw new Error(result.message || 'Generation failed.'); }, 'Generated questions saved for editorial review.'); }}><h2 class="font-semibold">Request AI practice drafts</h2><label class="label" for="ai-topic">Subject</label><input id="ai-topic" class="field" bind:value={subject} required /><p class="text-sm muted">Drafts enter the editorial queue before learners can practise with them.</p><button class="ctl" disabled={busy}>Generate five drafts</button></form>
	{/if}
	{#if domain === 'teams'}<form class="panel p-5 grid gap-3 mb-5" onsubmit={event => { event.preventDefault(); run(() => client.mutation(api.portal.createTeam, { name: teamName, blurb })); }}><h2 class="font-semibold">Create your team</h2><label class="label" for="team-name">Team name</label><input id="team-name" class="field" bind:value={teamName} required minlength="3" maxlength="100" /><label class="label" for="team-blurb">What will your team help people learn?</label><textarea id="team-blurb" class="field" bind:value={blurb} required maxlength="2000"></textarea><button class="ctl ctl-primary" disabled={busy}>Create team</button></form>{/if}
	{#if domain === 'threads' && detail}<section class="panel p-5 mb-5"><h2 class="font-semibold">Conversation</h2><ul class="grid gap-3 mt-4">{#each messages.data ?? [] as entry}<li class="panel-sunk p-3"><p class="text-xs muted">{entry.userId === profile.data?._id ? 'You' : 'Participant'}</p><p class="mt-1 whitespace-pre-wrap break-words">{entry.body}</p></li>{/each}</ul><form class="grid gap-3 mt-5" onsubmit={send}><label class="label" for="thread-message">Message</label><textarea id="thread-message" class="field" bind:value={message} required maxlength="4000"></textarea><button class="ctl ctl-primary" disabled={busy || !!messages.error}>Send message</button></form></section>{/if}
	{#if domain === 'family'}<div class="grid gap-3 mb-5">{#each rows('consents') as consent}<section class="panel p-5"><h2 class="font-semibold">{consent.scope}</h2><p class="muted mt-2">{consent.status}</p>{#if consent.status === 'pending'}<div class="flex gap-2 mt-4"><button class="ctl ctl-primary" disabled={busy} onclick={() => run(() => client.mutation(api.users.decideConsent, { consentId: consent._id, approve: true }))}>Approve</button><button class="ctl" disabled={busy} onclick={() => run(() => client.mutation(api.users.decideConsent, { consentId: consent._id, approve: false }))}>Decline</button></div>{/if}</section>{:else}<p class="panel p-5 muted">No guardian consent requests are waiting.</p>{/each}</div>{/if}
	{#if domain==='family'}
		{#if profile.data?.isMinor}<section class="panel p-5 mb-5"><h2 class="font-semibold">Invite your parent or guardian</h2><p class="muted text-sm mt-2">Share this private, single-use invitation with your guardian. It expires in 24 hours.</p><button class="ctl mt-4" disabled={busy} onclick={()=>run(async()=>{const result=await client.mutation(api.family.invite,{});inviteCode=result.token;},'Invitation created.')}>Create guardian invitation</button>{#if inviteCode}<code class="block break-all panel-sunk p-3 mt-3">{inviteCode}</code>{/if}</section>
		{:else}<form class="panel p-5 grid gap-3 mb-5" onsubmit={event=>{event.preventDefault();run(()=>client.mutation(api.family.accept,{token:guardianCode.trim(),acknowledge:guardianAck}),'Guardian link confirmed.');}}><h2 class="font-semibold">Link a learner</h2><label class="label" for="guardian-code">Invitation code from your child</label><input id="guardian-code" class="field" bind:value={guardianCode} required maxlength="100"/><label class="flex gap-3 text-sm"><input type="checkbox" bind:checked={guardianAck} required/>I am responsible for this learner and will review their paid learning requests.</label><button class="ctl ctl-primary" disabled={busy}>Accept guardian invitation</button></form>{/if}
		{#each rows('bookings').filter(x=>x.status==='pending_payment') as booking}<section class="panel p-5 mb-3"><h2 class="font-semibold">Approved learning support · {booking.topic}</h2><p class="muted mt-2">{naira(Number(booking.price))} · {booking.slot}</p><button class="ctl ctl-primary mt-3" disabled={busy} onclick={()=>payBooking(booking._id)}>Pay as linked guardian</button></section>{/each}
	{/if}
	{#if domain === 'settings'}
		<section class="panel p-5 mb-5"><h2 class="font-semibold">Your subscription</h2><p class="muted text-sm mt-2">View your current plan, expiry and renewal options. Feature access follows your verified subscription.</p><a href="/pricing" class="ctl mt-3">Manage plan and renew</a></section>
 <form class="panel p-5 grid gap-3 mb-5" onsubmit={event=>{event.preventDefault();run(async()=>{await client.mutation(api.portal.createTicket,{subject:supportSubject,body:supportBody});supportSubject='';supportBody='';},'Support request submitted. Its review status will update below.');}}><h2 class="font-semibold">Request support</h2><label class="label">Subject<input class="field mt-2" bind:value={supportSubject} required minlength="3" maxlength="150"/></label><label class="label">How can we help?<textarea class="field mt-2" bind:value={supportBody} required minlength="10" maxlength="5000"></textarea></label><button class="ctl" disabled={busy}>Submit for review</button></form>
		<form class="panel p-5 grid gap-3 mb-5" onsubmit={saveProfile}><h2 class="font-semibold">Your profile</h2><label class="label" for="profile-name">Name</label><input id="profile-name" class="field" placeholder={profile.data?.name} bind:value={name} maxlength="100" /><label class="label" for="profile-headline">Headline</label><input id="profile-headline" class="field" bind:value={headline} maxlength="200" /><ResidenceFields bind:state={residenceState} bind:lga bind:whatsapp bind:nin prefix="profile" required={false}/><p class="text-xs muted">Stored NIN: {profile.data?.ninLast4?`*******${profile.data.ninLast4}`:'Not submitted'}</p><button class="ctl ctl-primary" disabled={busy}>Save profile</button></form>
		<div class="panel p-5 grid gap-3 mb-5"><h2 class="font-semibold">Account data and files</h2><button class="ctl" disabled={busy} onclick={exportData}>Download my account data</button><label class="label" for="upload-kind">File visibility</label><select id="upload-kind" class="field" bind:value={uploadKind}><option value="document">Private document</option><option value="image">Public image (administrators only)</option></select><label class="label" for="account-upload">Upload a file</label><input id="account-upload" class="field" type="file" accept={uploadKind === 'image' ? 'image/jpeg,image/png,image/webp' : 'application/pdf'} disabled={busy} onchange={upload} /><a class="ctl" href="/forgot-password">Request password recovery</a></div>
		<div class="panel p-5 grid gap-3 mb-5"><h2 class="font-semibold">Add an earning role</h2><p class="text-sm muted">Paid publishing requires identity verification. Under-18 accounts cannot take earning roles.</p><div class="flex flex-wrap gap-2">{#each ['tutor', 'creator', 'ambassador'] as role}<button class="ctl" disabled={busy} onclick={() => run(() => client.mutation(api.users.requestRole, { role: role as 'tutor' | 'creator' | 'ambassador' }))}>Request {role} role</button>{/each}</div></div>
	{/if}
	{#if ['referrals','record'].includes(domain)}<EwinConnection attempts={data.attempts??[]}/>{/if}
 {#if domain === 'referrals' && profile.data}<section class="panel p-6 mb-5"><h2 class="font-semibold">Your referral link</h2><a class="link break-all block mt-4" href={`${APP_URL}/signup?ref=${profile.data.referralCode}`}>{APP_URL}/signup?ref={profile.data.referralCode}</a><p class="muted mt-3">Commissions are credited only after verified, eligible payments.</p></section>{/if}
	{#if domain==='inst'&&detail&&data.tenant}<InstitutionActions tenantId={detail as Id<'tenants'>} exams={data.exams??[]}/>{/if}
 {#if domain === 'ops'}
		<div class="grid sm:grid-cols-3 gap-4 mb-5">{#each [['New enquiries', rows('enquiries').filter(x => x.status === 'new').length], ['Content awaiting review', rows('submissions').length], ['Verification requests', rows('verifications').length]] as [label, n]}<div class="panel p-5"><p class="muted text-sm">{label}</p><p class="num text-3xl font-semibold mt-2">{n}</p></div>{/each}</div>
		<section class="panel p-5 mb-5"><h2 class="font-semibold text-xl">Enquiries</h2><div class="grid gap-3 mt-4">{#each rows('enquiries') as enquiry}<article class="panel-sunk p-4"><div class="flex flex-wrap justify-between gap-2"><h3 class="font-semibold">{enquiry.topic} · {enquiry.name}</h3><span class="badge">{enquiry.status.replaceAll('_', ' ')}</span></div><a class="link text-sm" href={`mailto:${enquiry.email}`}>{enquiry.email}</a><p class="text-sm mt-3 whitespace-pre-wrap">{enquiry.message}</p><div class="flex gap-2 mt-3"><button class="ctl ctl-sm" disabled={busy} onclick={() => run(() => client.mutation(api.portal.setEnquiryStatus, { id: enquiry._id, status: 'in_progress' }))}>Mark in progress</button><button class="ctl ctl-sm" disabled={busy} onclick={() => run(() => client.mutation(api.portal.setEnquiryStatus, { id: enquiry._id, status: 'closed' }))}>Close</button></div></article>{:else}<p class="muted">No enquiries have been submitted.</p>{/each}</div></section>
		<section class="panel p-5 mb-5"><h2 class="font-semibold">Publishing and account safety</h2><p class="muted mt-2 text-sm">Publishing, identity approval and access changes are recorded in the audit log.</p></section>
		<AdminOperations tickets={data.tickets??[]} reports={data.reports??[]} payouts={data.payouts??[]} events={data.ecosystemEvents??[]}/><AdminReview questions={data.questions??[]} verifications={data.verifications??[]} users={data.users??[]} />
	{/if}
	<div class="grid lg:grid-cols-2 gap-4">
	{#each Object.entries(data).filter(([key, value]) => Array.isArray(value) && !['bookings', 'consents', 'enquiries', ...(domain==='ops'?['questions','users','verifications','tickets','reports','payouts','ecosystemEvents']:[])].includes(key)) as [key, values]}
		<section class="panel p-5 min-w-0"><h2 class="font-semibold capitalize">{key.replace(/([A-Z])/g, ' $1')}</h2><ul class="grid gap-2 mt-4">{#each (values as Row[]).slice(0, 30) as row}<li class="panel-sunk p-3 text-sm"><div class="flex justify-between gap-3"><span class="font-medium break-words">{display(row)}</span>{#if row.status}<span class="badge h-fit">{String(row.status).replaceAll('_', ' ')}</span>{/if}</div>{#if row.body}<p class="muted mt-2 break-words">{row.body}</p>{/if}{#if row.pct !== undefined}<p class="num mt-2">{row.pct}% · {row.grade || ''}</p>{/if}{#if row.amount !== undefined}<p class="num mt-2">{naira(Number(row.amount))}</p>{/if}{#if row.theta !== undefined}<p class="muted mt-2">{row.answered} answered · {row.correct} correct</p>{/if}
			{#if key==='notifications'&&!row.read}<button class="ctl ctl-sm mt-2" disabled={busy} onclick={()=>run(()=>client.mutation(api.portal.readNotification,{id:row._id}))}>Mark as read</button>{/if}
 {#if key === 'threads'}<a class="link inline-block mt-2" href={`/threads/${row._id}`}>Open conversation</a>{/if}
			{#if key === 'tasks' && row.status === 'open'}<button class="ctl ctl-sm mt-2" disabled={busy} onclick={() => run(() => client.mutation(api.collab.claimTask, { taskId: row._id }))}>Claim task</button>{/if}
			{#if key === 'documents'}<a class="link inline-block mt-2" href={`/api/media/documents/${encodeURIComponent(row.key)}`}>Download private document</a>{/if}
		</li>{:else}<li class="muted text-sm">No records yet. New activity will appear here automatically.</li>{/each}</ul></section>
	{/each}
	</div>
{/if}
