<script lang="ts">
 import { useQuery, useConvexClient } from 'convex-svelte';
 import { api } from '$convex/_generated/api';
 import type { Id } from '$convex/_generated/dataModel';
 import { naira } from '$ui/format';
 const client=useConvexClient(),dashboard=useQuery(api.tutorBundles.dashboard,{});
 let busy=$state(false),error=$state(''),notice=$state('');
 let budget=$state<number|undefined>(undefined),enable=$state(false),offerId=$state(''),capacity=$state(1),slotsText=$state('');
 let subjects=$state<Record<string,string>>({}),goals=$state<Record<string,string>>({}),chosen=$state<Record<string,string>>({}),notes=$state<Record<string,string>>({});
 let slots=$state<Record<string,string>>({}),urls=$state<Record<string,string>>({}),drafts=$state<Record<string,string>>({}),ownWork=$state<Record<string,boolean>>({});
 let covered=$state<Record<string,string>>({}),progress=$state<Record<string,string>>({}),homework=$state<Record<string,string>>({}),feedback=$state<Record<string,string>>({}),reasons=$state<Record<string,string>>({});
 async function run(task:()=>Promise<unknown>,message:string){busy=true;error='';notice='';try{await task();notice=message;}catch(e){error=e instanceof Error?e.message:'Unable to save the change.';}finally{busy=false;}}
 function download(title:string,body:string){const url=URL.createObjectURL(new Blob([`# ${title}\n\nOriginal SchoolXense learning worksheet\n\n${body}\n`],{type:'text/markdown'}));const a=document.createElement('a');a.href=url;a.download=`schoolxense-${title.replaceAll(/[^a-z0-9]+/gi,'-')}.md`;a.click();URL.revokeObjectURL(url);}
 function saveAvailability(event:SubmitEvent){event.preventDefault();return run(()=>client.mutation(api.tutorBundles.availability,{offerId:offerId as Id<'offers'>,capacity,slots:slotsText.split('\n').map(s=>Date.parse(s.trim())).filter((_,i)=>!!slotsText.split('\n')[i].trim())}),'Availability saved for staff approval.');}
</script>

<div class="grid gap-5">
 {#if error}<p class="panel-sunk p-4 break-words" role="alert">{error}</p>{/if}
 {#if notice}<p class="panel-sunk p-4" role="status">{notice}</p>{/if}
 {#if dashboard.error}<p class="panel p-5" role="alert">Unable to load tutor bundles: {dashboard.error.message}</p>{:else if !dashboard.data}<p role="status">Loading your tutor bundle…</p>{:else}
 {@const data=dashboard.data}
 <section class="panel p-5"><div class="flex flex-wrap justify-between gap-3"><h2 class="text-xl font-semibold">Six sessions, a clear learning plan</h2><a class="ctl ctl-sm" href="/pricing">View plans</a></div><p class="text-sm muted mt-3">{data.guide}</p><p class="text-sm mt-3">Bundle sales: <b>{data.policy?.enabled?'enabled, subject to approved capacity':'awaiting administrator activation'}</b>. Payment provider activation is a separate production gate.</p></section>
 {#if data.staff}
 <form class="panel p-5 grid sm:grid-cols-2 gap-3" onsubmit={(e)=>{e.preventDefault();run(()=>client.mutation(api.tutorBundles.configure,{enabled:enable,sessionKobo:BigInt(Math.round((budget??0)*100))}),'Bundle compensation policy saved and audited.');}}>
  <h2 class="font-semibold text-xl sm:col-span-2">Bundle compensation policy</h2><p class="text-sm muted sm:col-span-2">Approve the session service budget before any sale. Six times this amount is held from the ₦25,000 purchase; the balance funds learning access. Each delivered session uses the existing marketplace Hive Share. Published tutor availability must accept the same budget. Changes apply to future orders; existing payments keep their recorded budget.</p>
  <p class="sm:col-span-2 text-sm">Current budget: {data.policy?`${naira(Number(data.policy.sessionKobo))} per session`:'not configured'}.</p>
  <label class="label">Session service budget (₦)<input type="number" class="field mt-2" min="500" max="4166" step="1" required bind:value={budget}/></label><label class="flex items-center gap-2"><input type="checkbox" bind:checked={enable}/>Enable bundle sales and allocation</label>
  <button class="ctl ctl-primary sm:col-span-2" disabled={busy}>Approve policy</button>
 </form>
 <section class="panel p-5"><h2 class="font-semibold text-xl">Tutor capacity and approval</h2><p class="text-sm muted mt-2">Only adults with verified identity, a trusted tutor role and an active tutoring offer can join. Under-18 matching additionally requires approved safeguarding.</p><div class="grid gap-3 mt-4">{#each data.roster as row}<article class="panel-sunk p-4"><p class="font-semibold">{data.offers.find(o=>o._id===row.offerId)?.title??row.offerId}</p><p class="text-sm muted mt-2">{row.approved?'Approved':'Awaiting review'} · {row.capacity} active bundles · {row.slots.filter(s=>s>Date.now()).length} future slots · {naira(Number(row.sessionKobo))} per session</p><div class="flex flex-wrap gap-2 mt-3"><button class="ctl ctl-sm" disabled={busy||row.approved} onclick={()=>run(()=>client.mutation(api.tutorBundles.approveRoster,{id:row._id,approved:true}),'Tutor capacity approved.')}>Approve tutor capacity</button><button class="ctl ctl-sm" disabled={busy||!row.approved} onclick={()=>run(()=>client.mutation(api.tutorBundles.approveRoster,{id:row._id,approved:false}),'Tutor capacity paused.')}>Pause allocation</button></div></article>{:else}<p class="muted">No tutors have submitted bundle availability.</p>{/each}</div></section>
 {/if}
 {#if data.tutor}
 <form class="panel p-5 grid sm:grid-cols-2 gap-3" onsubmit={saveAvailability}><h2 class="font-semibold text-xl sm:col-span-2">Offer bundle availability</h2><p class="text-sm muted sm:col-span-2">Submitting accepts the configured {data.policy?naira(Number(data.policy.sessionKobo)):'unset'} session budget before Hive Share. Publish at least six distinct 45-minute slots. Use ISO dates with timezone, for example 2026-11-01T14:00:00+01:00.</p><label class="label">Your tutoring offer<select class="field mt-2" required bind:value={offerId}><option value="">Choose offer</option>{#each data.offers.filter(o=>o.tutorId===data.userId&&o.active&&o.kind==='tutoring') as offer}<option value={offer._id}>{offer.title}</option>{/each}</select></label><label class="label">Maximum concurrent bundles<input class="field mt-2" type="number" min="1" max="30" required bind:value={capacity}/></label><label class="label sm:col-span-2">Available starts (one ISO date per line)<textarea class="field mt-2" rows="6" required bind:value={slotsText}></textarea></label><button class="ctl ctl-primary sm:col-span-2" disabled={busy||!data.policy}>Accept budget and submit availability</button><a href="/offers" class="link">Manage tutoring offers</a></form>
 {/if}
 {#each data.bundles as bundle}
 {@const canManage=data.staff||bundle.userId===data.userId||bundle.guardian}
 {@const canReview=bundle.userId===data.userId||bundle.guardian}
 {@const isTutor=bundle.tutorId===data.userId}
 <section class="panel p-5 min-w-0"><div class="flex flex-wrap justify-between gap-3"><div><h2 class="font-semibold text-xl">{bundle.learnerName} · {bundle.subject??'Choose a subject'}</h2><p class="muted text-sm mt-2">{bundle.tutorName} · Expires {new Date(bundle.expiresAt).toLocaleDateString()} · {bundle.sessions.filter(s=>s.status==='completed').length}/6 completed</p></div><span class="badge h-fit">{!bundle.paid?'Payment requires review':bundle.expired?'Expired':bundle.status.replaceAll('_',' ')}</span></div>
 {#if bundle.goal}<p class="mt-3 text-sm whitespace-pre-wrap break-words">Goal: {bundle.goal}</p>{/if}
 {#if bundle.paid&&!bundle.expired&&canManage&&['needs_preferences','awaiting_tutor'].includes(bundle.status)}<form class="grid sm:grid-cols-2 gap-3 mt-4" onsubmit={(e)=>{e.preventDefault();run(()=>client.mutation(api.tutorBundles.preferences,{bundleId:bundle._id,subject:subjects[bundle._id]??'',goal:goals[bundle._id]??''}),'Preferences sent for matching.');}}><label class="label">Subject<input class="field mt-2" required minlength="2" maxlength="120" bind:value={subjects[bundle._id]}/></label><label class="label">Learning goal<textarea class="field mt-2" required minlength="10" maxlength="1000" bind:value={goals[bundle._id]}></textarea></label><button class="ctl sm:col-span-2" disabled={busy}>Request tutor allocation</button></form>{/if}
 {#if data.staff&&bundle.subject&&!bundle.expired&&bundle.paid&&bundle.status!=='completed'}<form class="grid sm:grid-cols-2 gap-3 mt-4" onsubmit={(e)=>{e.preventDefault();run(()=>client.mutation(api.tutorBundles.allocate,{bundleId:bundle._id,offerId:chosen[bundle._id] as Id<'offers'>,note:notes[bundle._id]??''}),'Tutor allocated with an audit record.');}}><label class="label">Approved matching tutor<select class="field mt-2" required bind:value={chosen[bundle._id]}><option value="">Choose tutor</option>{#each bundle.candidates as candidate}<option value={candidate.offerId}>{candidate.name} · capacity {candidate.capacity}</option>{/each}</select></label><label class="label">Allocation rationale<textarea class="field mt-2" required minlength="10" maxlength="1000" bind:value={notes[bundle._id]}></textarea></label><button class="ctl sm:col-span-2" disabled={busy||!bundle.candidates.length}>Allocate or reassign tutor</button></form>{/if}
 {#if bundle.status==='allocated'&&!bundle.guardianApproved}<p class="panel-sunk p-3 mt-4 text-sm">A linked guardian must approve this tutor before sessions can be scheduled.</p>{#if bundle.guardian}<button class="ctl mt-3" disabled={busy} onclick={()=>run(()=>client.mutation(api.tutorBundles.consent,{bundleId:bundle._id}),'Guardian approval recorded.')}>Approve tutor as linked guardian</button>{/if}{/if}
 <div class="grid gap-3 mt-5">{#each bundle.sessions as session}
 <article class="panel-sunk p-4 min-w-0"><div class="flex flex-wrap justify-between gap-2"><h3 class="font-semibold">Session {session.ordinal} · 45 minutes</h3><span class="badge">{session.status.replaceAll('_',' ')}</span></div>{#if session.startsAt}<p class="muted text-sm mt-2">{new Date(session.startsAt).toLocaleString()}</p>{/if}
 {#if session.status==='available'&&canManage&&bundle.status==='allocated'&&bundle.guardianApproved&&!bundle.expired&&bundle.paid}<form class="flex flex-wrap gap-3 mt-3" onsubmit={(e)=>{e.preventDefault();run(()=>client.mutation(api.tutorBundles.schedule,{sessionId:session._id,startsAt:Number(slots[session._id])}),'Session scheduled.');}}><label class="label flex-1 min-w-0">Tutor start time<select class="field mt-2" required bind:value={slots[session._id]}><option value="">Select available start</option>{#each bundle.slots as slot}<option value={String(slot)}>{new Date(slot).toLocaleString()}</option>{/each}</select></label><button class="ctl self-end" disabled={busy||!bundle.slots.length}>Reserve session</button></form>{/if}
 {#if session.status==='scheduled'}<div class="flex flex-wrap gap-2 mt-3">{#if session.meetingUrl}<a class="ctl ctl-primary" href={session.meetingUrl} target="_blank" rel="noopener noreferrer">Join tutor session</a>{:else}<p class="text-sm muted">Meeting link opens 15 minutes before the session after the tutor adds it.</p>{/if}{#if session.threadId}<a class="ctl ctl-sm" href={`/threads/${session.threadId}`}>Session conversation</a>{/if}{#if canManage}<button class="ctl ctl-sm" disabled={busy||(!data.staff&&!!session.startsAt&&session.startsAt-Date.now()<86400000)} onclick={()=>run(()=>client.mutation(api.tutorBundles.cancel,{sessionId:session._id}),'Credit returned. Select a new time to reschedule.')}>Cancel / reschedule</button>{/if}</div>
 {#if isTutor&&!bundle.expired}<form class="flex flex-wrap gap-3 mt-3" onsubmit={(e)=>{e.preventDefault();run(()=>client.mutation(api.tutorBundles.meeting,{sessionId:session._id,url:urls[session._id]??''}),'Secure meeting link saved.');}}><label class="label flex-1 min-w-0">Google Meet or Zoom URL<input class="field mt-2" type="url" required bind:value={urls[session._id]}/></label><button class="ctl self-end" disabled={busy}>Save meeting link</button></form>{/if}
 {#if bundle.userId===data.userId&&!bundle.expired}<details class="mt-4"><summary class="cursor-pointer font-semibold">Submit your own draft for feedback</summary><form class="grid gap-3 mt-3" onsubmit={(e)=>{e.preventDefault();run(()=>client.mutation(api.tutorBundles.draft,{sessionId:session._id,draft:drafts[session._id]??'',ownWork:ownWork[session._id]??false}),'Draft saved for your assigned tutor.');}}><label class="label">Your draft<textarea class="field mt-2" rows="5" required minlength="20" maxlength="10000" bind:value={drafts[session._id]}></textarea></label><label class="flex gap-2 text-sm"><input type="checkbox" required bind:checked={ownWork[session._id]}/>I wrote this draft and am requesting feedback, not completion of assessed work.</label><button class="ctl" disabled={busy}>Share draft privately</button></form></details>{/if}
 {/if}
 {#if session.draft}<details class="mt-4"><summary class="cursor-pointer font-semibold">Learner draft</summary><p class="text-sm whitespace-pre-wrap break-words mt-3">{session.draft}</p></details>{/if}
 {#if isTutor&&session.status==='scheduled'&&!bundle.expired}<form class="grid gap-3 mt-4" onsubmit={(e)=>{e.preventDefault();run(()=>client.mutation(api.tutorBundles.report,{sessionId:session._id,covered:covered[session._id]??'',progress:progress[session._id]??'',homework:homework[session._id]??'',feedback:feedback[session._id]??''}),'Session report submitted for learner review.');}}><h4 class="font-semibold">Session report</h4>{#each [{label:'What we covered',store:covered},{label:'Evidence of progress',store:progress},{label:'Next practice / homework',store:homework}] as field}<label class="label">{field.label}<textarea class="field mt-2" required minlength="10" maxlength="2000" bind:value={field.store[session._id]}></textarea></label>{/each}{#if session.draft}<label class="label">Draft feedback<textarea class="field mt-2" required minlength="10" maxlength="4000" bind:value={feedback[session._id]}></textarea></label>{/if}<button class="ctl" disabled={busy||!session.startsAt||Date.now()<session.startsAt+2700000}>Submit report after session</button></form>{/if}
 {#if session.report}<div class="grid gap-2 mt-4 text-sm"><p class="whitespace-pre-wrap break-words"><b>Covered:</b> {session.report.covered}</p><p class="whitespace-pre-wrap break-words"><b>Progress:</b> {session.report.progress}</p><p class="whitespace-pre-wrap break-words"><b>Next practice:</b> {session.report.homework}</p>{#if session.feedback}<p class="whitespace-pre-wrap break-words"><b>Draft feedback:</b> {session.feedback}</p>{/if}<button class="ctl ctl-sm w-fit" onclick={()=>download(`Session ${session.ordinal} report`,`${session.report?.covered}\n\nProgress: ${session.report?.progress}\n\nHomework: ${session.report?.homework}\n\nFeedback: ${session.feedback??'No draft submitted'}`)}>Download report</button></div>{/if}
 {#if canReview&&session.status==='under_review'}<button class="ctl ctl-primary mt-4" disabled={busy} onclick={()=>run(()=>client.mutation(api.tutorBundles.confirm,{sessionId:session._id}),'Delivery confirmed. Funded session share queued for settlement.')}>Confirm session delivery</button>{/if}
 {#if canReview&&['scheduled','under_review'].includes(session.status)}<details class="mt-4"><summary class="cursor-pointer text-sm">Report a session issue / no-show</summary><label class="label mt-3">Issue<textarea class="field mt-2" minlength="10" maxlength="2000" bind:value={reasons[session._id]}></textarea></label><button class="ctl mt-3" disabled={busy||(reasons[session._id]??'').trim().length<10} onclick={()=>run(()=>client.mutation(api.tutorBundles.dispute,{sessionId:session._id,reason:reasons[session._id]??''}),'Session flagged for staff review; funds remain held.')}>Open dispute</button></details>{/if}
 {#if session.status==='disputed'}<p class="text-sm mt-3 break-words">Issue: {session.dispute}</p>{#if data.staff}<label class="label mt-3">Review decision rationale<textarea class="field mt-2" minlength="10" maxlength="2000" bind:value={reasons[session._id]}></textarea></label><div class="flex flex-wrap gap-2 mt-3">{#each ['restore_credit','confirm_delivery'] as decision}<button class="ctl ctl-sm" disabled={busy||(reasons[session._id]??'').trim().length<10} onclick={()=>run(()=>client.mutation(api.tutorBundles.resolveDispute,{sessionId:session._id,decision:decision as 'restore_credit'|'confirm_delivery',note:reasons[session._id]??''}),'Dispute decision saved and participants notified.')}>{decision==='restore_credit'?'Restore session credit':'Confirm evidenced delivery'}</button>{/each}</div>{/if}{/if}
 </article>{/each}</div>
 </section>
 {:else}<section class="panel p-5"><h2 class="text-xl font-semibold">No tutor bundles yet</h2><p class="text-sm muted mt-2">Verified bundle purchases appear here automatically. No sample purchases or tutors are created.</p></section>{/each}
 <section class="panel p-5"><h2 class="text-xl font-semibold">Session resources</h2><p class="text-sm muted mt-2">Original preparation and follow-up worksheets. Adapt them with your tutor for your subject.</p><div class="grid sm:grid-cols-2 gap-3 mt-4">{#each data.resources as resource}<article class="panel-sunk p-4"><h3 class="font-semibold">{resource.title}</h3><p class="whitespace-pre-wrap text-sm muted mt-3">{resource.body}</p><button class="ctl ctl-sm mt-3" onclick={()=>download(resource.title,resource.body)}>Download worksheet</button></article>{/each}</div></section>
 {/if}
</div>
