<script lang="ts">
 import {useQuery,useConvexClient} from 'convex-svelte';
 import {api} from '$convex/_generated/api';
 import type {Doc} from '$convex/_generated/dataModel';
 let {events=[]}:{events?:Doc<'ecosystemEvents'>[]}=$props();
 const client=useConvexClient(),queue=useQuery(api.disputes.queue,{});
 let notes=$state<Record<string,string>>({}),busy=$state(false),error=$state(''),notice=$state('');
 async function run(work:()=>Promise<unknown>){busy=true;error='';notice='';try{await work();notice='Decision saved. Provider completion remains separate from approval.';}catch(e){error=e instanceof Error?e.message:'Unable to update workflow.';}finally{busy=false;}}
</script>
<section class="panel p-5 mb-5"><h2 class="font-semibold text-xl">Booking disputes and refunds</h2><p class="muted text-sm mt-2">Independent review is required. Funds stay frozen until release or a verified provider refund.</p>
{#if error}<p role="alert" class="mt-3">{error}</p>{/if}{#if notice}<p role="status" class="mt-3">{notice}</p>{/if}
{#each queue.data?.disputes??[] as row}<article class="panel-sunk p-4 mt-3"><p>{row.reason}</p><span class="badge mt-2">{row.status.replaceAll('_',' ')}</span>{#if ['open','under_review'].includes(row.status)}<label class="label block mt-3">Review evidence<textarea class="field mt-2" bind:value={notes[row._id]} minlength="10" maxlength="2000"></textarea></label><div class="flex flex-wrap gap-2 mt-3">{#each ['under_review','release','refund'] as decision}<button class="ctl ctl-sm" disabled={busy||(notes[row._id]??'').trim().length<10} onclick={()=>run(()=>client.mutation(api.disputes.decide,{id:row._id,decision:decision as 'under_review'|'release'|'refund',note:notes[row._id]}))}>{decision==='refund'?'Approve provider refund':decision==='release'?'Confirm delivery and release':'Start review'}</button>{/each}</div>{/if}{#if row.decisionNote}<p class="text-sm muted mt-2">{row.decisionNote}</p>{/if}</article>{:else}<p class="muted mt-3">No booking disputes.</p>{/each}
{#each queue.data?.refunds??[] as refund}<p class="panel-sunk p-3 mt-2 text-sm">Refund {refund._id}: {refund.status}{refund.lastError?' · '+refund.lastError:''}</p>{/each}</section>
<section class="panel p-5 mb-5"><h2 class="font-semibold text-xl">E-WIN delivery recovery</h2>{#each events.filter(x=>!x.deliveredAt&&(x.attempts??0)>0) as event}<article class="panel-sunk p-4 mt-3"><p>{event.type} · {event.quarantinedAt?'Quarantined':'Retry scheduled'} · {event.attempts} attempts</p><p class="muted text-sm mt-2">{event.lastError}</p><label class="label block mt-3">Replay rationale<textarea class="field mt-2" bind:value={notes[event._id]} minlength="10" maxlength="1000"></textarea></label><button class="ctl mt-3" disabled={busy||(notes[event._id]??'').trim().length<10} onclick={()=>run(()=>client.mutation(api.ecosystem.replay,{id:event._id,note:notes[event._id]}))}>Request audited replay</button></article>{:else}<p class="muted mt-3">No failed events in this page of delivery records.</p>{/each}</section>
