name = "schoolxense-realtime-rooms"
main = "src/index.ts"
compatibility_date = "2026-09-01"
workers_dev = false

[vars]
ROOMS_ENABLED = "false"

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "Room"

[[migrations]]
tag = "v1"
new_classes = ["Room"]

[[r2_buckets]]
binding = "SNAPSHOTS"
bucket_name = "schoolxense-room-snapshots"
