/** Original SchoolXense worksheets. Tutors adapt examples to the learner's subject. */
export const BUNDLE_RESOURCES = [
 {title:'1. Diagnose and set a goal',body:'Before: bring three attempted questions and mark where you got stuck.\nDuring: explain your reasoning aloud; build an error log with columns Question / My method / Gap / Next step. Agree one measurable goal.\nAfter: retry one question unaided and record what changed.'},
 {title:'2. Build the foundations',body:'Before: list five terms or rules from the difficult topic and define them in your own words.\nDuring: connect each rule to an example and a counterexample. Solve one worked example together, then a parallel problem independently.\nAfter: make five retrieval cards; include units, assumptions and common errors.'},
 {title:'3. Apply and explain',body:'Before: attempt two unfamiliar problems without copying a solution.\nDuring: identify known values, the unknown, the governing rule and a reasonableness check. Explain each step to the tutor.\nAfter: solve three variations; record accuracy and confidence before checking.'},
 {title:'4. Review your own draft',body:'Before: paste a draft you wrote yourself and describe the feedback you need. Do not submit a live exam or ask someone to write assessed work.\nDuring: check clarity, evidence, structure and reasoning. The tutor gives comments and questions; the learner makes the edits.\nAfter: keep a before/after passage and explain the revision choices.'},
 {title:'5. Practise under time limits',body:'Before: choose a short set of reviewed practice questions.\nDuring: complete a timed attempt, flag uncertain answers, then compare your reasoning with feedback. Categorise mistakes as knowledge, method, reading or timing.\nAfter: target the most frequent error type with a short daily drill.'},
 {title:'6. Consolidate and plan',body:'Before: retry the diagnostic questions from session one.\nDuring: compare evidence against your goal; explain a solution without prompts. Agree a realistic next study plan and warning signs for topics that need another review.\nAfter: schedule spaced reviews at 1, 3, 7 and 14 days. Record progress rather than assuming a guaranteed exam score.'}
] as const;
export const BUNDLE_GUIDE='Six 45-minute sessions within 90 days of payment fulfilment. Scheduling uses tutor-published slots. Cancel or reschedule at least 24 hours before the session; later changes need administrator review. A report and draft feedback are required before completion. Under-18 learners need a linked guardian to approve the tutor, and the guardian is included in the session thread. Meeting links open 15 minutes before the session. Unused or disputed funds remain held for administrator reconciliation; they are not automatically paid to a tutor.';
