import { test, expect, vi, afterEach } from 'vitest';
import { convexTest } from 'convex-test';
import schema from '../../convex/schema';
import { api } from '../../convex/_generated/api';
vi.mock('../../convex/auth',()=>({authComponent:{safeGetAuthUser:async(ctx:any)=>{const i=await ctx.auth.getUserIdentity();return i?{_id:i.subject,emailVerified:i.emailVerified}:null;}}}));
vi.mock('../../convex/rateLimits',()=>({rateLimiter:{limit:vi.fn(async()=>({ok:true}))}}));
const modules=import.meta.glob('../../convex/**/*.ts');
const q={topic:'Forces',stem:'Which unit measures force?',options:['Newton','Joule','Watt','Pascal'],answer:0,explanation:'Force is measured in newtons in the SI system.'};
async function fixture(){const t=convexTest(schema,modules);const actor=await t.run(async ctx=>{const id=await ctx.db.insert('users',{authId:'owner',name:'Owner',isMinor:false,profileComplete:true,dailyMinutes:15,referralCode:'owner',creditsDays:0,streak:0,status:'active'});await ctx.db.insert('roles',{userId:id,role:'staff',grantedAt:Date.now()});return id;});return {t,actor,staff:t.withIdentity({subject:'owner',emailVerified:true})};}
afterEach(()=>{vi.unstubAllGlobals();vi.unstubAllEnvs();vi.restoreAllMocks();});
test('configuration alone is never represented as a successful live AI request',async()=>{const f=await fixture();vi.stubEnv('AGNES_AI_KEY','test-key');const h=await f.staff.query(api.admin.health,{});expect(h.ai.status).toBe('configured');expect(h.ai.lastRun).toBeNull();});
test('validated AGNES response persists independent-review drafts and live evidence',async()=>{const f=await fixture();vi.stubEnv('AGNES_AI_KEY','test-key');vi.stubGlobal('fetch',vi.fn(async()=>Response.json({choices:[{message:{content:JSON.stringify([q])}}]})));const result=await f.staff.action(api.ai.generate,{exam:'JAMB',subject:'Physics',count:1});expect(result.stored).toBe(1);const h=await f.staff.query(api.admin.health,{});expect(h.ai.lastRun?.status).toBe('succeeded');expect(h.ai.lastRun?.provider).toBe('agnes');expect(h.ai.lastRun?.primaryFailed).toBe(false);const question=await f.t.run(ctx=>ctx.db.query('questions').first());expect(question?.status).toBe('unreviewed');expect(question?.authorId).toBe(f.actor);await expect(f.staff.mutation(api.admin.reviewQuestion,{id:question!._id,approve:true})).rejects.toThrow('different reviewer');});
test('fallback evidence distinguishes AGNES failure from Workers AI success',async()=>{const f=await fixture();vi.stubEnv('AGNES_AI_KEY','test-key');vi.stubEnv('CLOUDFLARE_AI_TOKEN','test-key');vi.stubEnv('CLOUDFLARE_ACCOUNT_ID','test-account');vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce(new Response('',{status:503})).mockResolvedValueOnce(Response.json({result:{response:JSON.stringify([q])}})));await f.staff.action(api.ai.generate,{exam:'JAMB',subject:'Physics',count:1});const h=await f.staff.query(api.admin.health,{});expect(h.ai.lastRun?.provider).toBe('workers_ai');expect(h.ai.lastRun?.primaryFailed).toBe(true);expect(h.ai.lastRun?.status).toBe('succeeded');});
test('invalid provider output fails closed, records failure and publishes no question',async()=>{const f=await fixture();vi.stubEnv('AGNES_AI_KEY','test-key');vi.stubEnv('CLOUDFLARE_AI_TOKEN','');vi.stubGlobal('fetch',vi.fn(async()=>Response.json({choices:[{message:{content:'invalid output'}}]})));await expect(f.staff.action(api.ai.generate,{exam:'JAMB',subject:'Physics',count:1})).rejects.toThrow('No content was published');expect((await f.staff.query(api.admin.health,{})).ai.lastRun?.status).toBe('failed');expect(await f.t.run(ctx=>ctx.db.query('questions').collect())).toHaveLength(0);});
