import { describe,test,expect,vi } from 'vitest';
import { convexTest } from 'convex-test';
import schema from '../../convex/schema';
import { api,internal } from '../../convex/_generated/api';
import { activeHold } from '../../convex/lib/tutorBundle';
import { verifyRoomToken } from '../../workers/realtime-rooms/src/token';
import { verifyEwinLink,type EwinLinkAssertion } from '../../convex/lib/ewinLink';
vi.mock('../../convex/auth',()=>({authComponent:{safeGetAuthUser:async(ctx:any)=>{const i=await ctx.auth.getUserIdentity();return i?{_id:i.subject,emailVerified:true}:null;}}}));
vi.mock('../../convex/components',()=>({workflows:{start:vi.fn()},attemptAggregate:{insert:vi.fn()}}));
const modules=import.meta.glob('../../convex/**/*.ts');
async function fixture(){const t=convexTest(schema,modules);const rows=await t.run(async ctx=>{
 const add=async(authId:string)=>ctx.db.insert('users',{authId,name:authId,isMinor:false,profileComplete:true,dailyMinutes:15,referralCode:authId,creditsDays:0,streak:0,status:'active'});
 const learner=await add('learner'),tutor=await add('tutor'),other=await add('other');
 for(const [userId,role]of [[learner,'learner'],[tutor,'staff'],[tutor,'tutor'],[other,'tutor']]as const)await ctx.db.insert('roles',{userId,role,grantedAt:Date.now()});
 const slot=new Date(Date.now()+86400000).toISOString();
 const offer=await ctx.db.insert('offers',{tutorId:tutor,kind:'tutoring',title:'Physics support',subjects:['Physics'],topics:[],levels:[],languages:['English'],price:250000n,availability:[slot],module:'tutors',active:true,minorsApproved:false,rating:0,reviews:0,completion:0,sessions:0});
 const target=await ctx.db.insert('offers',{tutorId:other,kind:'tutoring',title:'Alternate tutor',subjects:['Physics'],topics:[],levels:[],languages:['English'],price:250000n,availability:[slot],module:'tutors',active:true,minorsApproved:false,rating:0,reviews:0,completion:0,sessions:0});return{learner,tutor,other,offer,target,slot};});return{t,...rows,a:t.withIdentity({subject:'learner'}),teacher:t.withIdentity({subject:'tutor'})};}
describe('Production workflow security',()=>{
 test('account linking preserves referral attribution and cannot grant roles or subscriptions',async()=>{const f=await fixture();await f.t.run(ctx=>ctx.db.patch(f.learner,{ecosystemId:'schoolxense:learner',centralReferralCode:'ORIGINAL-REFERRER'}));const assertion={version:1 as const,platformId:'schoolcbt' as const,platformSubject:'schoolxense:learner',centralUserId:'central-member',linkId:'central-link',referralCode:'MEMBERS-OWN-CODE',issuedAt:Date.now(),expiresAt:Date.now()+300000};await f.a.mutation(internal.ecosystem.persistAccountLink,{assertion});const user=await f.t.run(ctx=>ctx.db.get(f.learner));expect(user?.centralUserId).toBe('central-member');expect(user?.centralReferralCode).toBe('ORIGINAL-REFERRER');expect(await f.t.run(ctx=>ctx.db.query('subscriptions').collect())).toHaveLength(0);expect((await f.t.run(ctx=>ctx.db.query('roles').withIndex('by_user',q=>q.eq('userId',f.learner)).collect())).map(x=>x.role)).toEqual(['learner']);await expect(f.a.mutation(internal.ecosystem.persistAccountLink,{assertion:{...assertion,platformSubject:'schoolxense:other'}})).rejects.toThrow('subject does not match');});
 test('published slots are required and ordinary booking overlap is rejected',async()=>{const f=await fixture();const args={offerId:f.offer,slot:f.slot,minutes:45,topic:'Resultant force'};await f.a.mutation(api.market.create,args);await expect(f.a.mutation(api.market.create,args)).rejects.toThrow('SLOT_ALREADY_RESERVED');await expect(f.a.mutation(api.market.create,{...args,slot:new Date(Date.parse(f.slot)+86400000).toISOString()})).rejects.toThrow('SLOT_NOT_OFFERED');});
 test('delivery cannot start the escrow clock before the session ends',async()=>{const f=await fixture();const id=await f.a.mutation(api.market.create,{offerId:f.offer,slot:f.slot,minutes:45,topic:'Resultant force'});await f.t.run(ctx=>ctx.db.patch(id,{status:'confirmed'}));await expect(f.teacher.mutation(api.market.deliver,{bookingId:id})).rejects.toThrow('SESSION_NOT_FINISHED');expect((await f.t.run(ctx=>ctx.db.get(id)))?.status).toBe('confirmed');});
 test('handoff revalidates destination subscription and does not change recipients on rejection',async()=>{const f=await fixture();const id=await f.a.mutation(api.market.create,{offerId:f.offer,slot:f.slot,minutes:45,topic:'Resultant force'});await f.t.run(ctx=>ctx.db.patch(id,{status:'confirmed'}));await expect(f.teacher.mutation(api.market.handoff,{bookingId:id,toOfferId:f.target})).rejects.toThrow('SUBSCRIPTION_REQUIRED');expect((await f.t.run(ctx=>ctx.db.get(id)))?.tutorId).toBe(f.tutor);});
 test('outbox failure has backoff and quarantine without hiding later events',async()=>{const f=await fixture();const ids=await f.t.run(async ctx=>Promise.all([1,2].map(()=>ctx.db.insert('ecosystemEvents',{eventId:crypto.randomUUID(),app:'schoolxense',type:'identity.created',subject:'schoolxense:test',payload:{version:1},createdAt:Date.now()}))));await f.t.mutation(internal.ecosystem.failed,{id:ids[0],reason:'HTTP 400',permanent:true});const pending=await f.t.query(internal.ecosystem.pending,{});expect(pending.map(x=>x._id)).toEqual([ids[1]]);await expect(f.a.mutation(api.ecosystem.replay,{id:ids[0],note:'Reviewed the report schema.'})).rejects.toThrow('FORBIDDEN');await f.teacher.mutation(api.ecosystem.replay,{id:ids[0],note:'Reviewed the report schema.'});expect(await f.t.query(internal.ecosystem.pending,{})).toHaveLength(2);});
 test('checkout holds expire at the boundary',()=>{expect(activeHold({createdAt:1000},1800999)).toBe(true);expect(activeHold({createdAt:1000},1801000)).toBe(false);});
 test('closed royalty period is paid once and excludes current-month usage/funding',async()=>{const f=await fixture();const now=new Date(),month=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()-1,1)).toISOString().slice(0,7);await f.t.run(async ctx=>{const wallet=await ctx.db.insert('wallets',{system:'royalty_pool',currency:'NGN'});await ctx.db.insert('ledgerEntries',{walletId:wallet,txnId:'fund',amount:10000n,currency:'NGN',kind:'royalty',memo:'fund',createdAt:Date.parse(month+'-15')});const q=await ctx.db.insert('questions',{exam:'jamb',subject:'Physics',topic:'Force',stem:'Question',options:['a','b','c','d'],answer:0,explanation:'Because',a:1,b:0,bloom:'apply',status:'reviewed',licence:'test',contentHash:'test',authorId:f.tutor});await ctx.db.insert('paidQuestionUsage',{month,questionId:q,authorId:f.tutor,serves:2});});await f.t.mutation(internal.studio.computeMonthly,{});await f.t.mutation(internal.studio.computeMonthly,{});expect(await f.t.run(ctx=>ctx.db.query('royaltyRuns').collect())).toHaveLength(1);expect(await f.t.run(ctx=>ctx.db.query('questionRoyalties').collect())).toHaveLength(1);});
 test('room verifier rejects missing, tampered and cross-room credentials',async()=>{const secret='a'.repeat(48),iat=Math.floor(Date.now()/1000);const enc=(x:any)=>Buffer.from(JSON.stringify(x)).toString('base64url');const body=enc({alg:'HS256',typ:'JWT'})+'.'+enc({iss:'schoolxense',aud:'schoolxense-room',room:'one',origin:'https://schoolxense.ewinproject.org',sub:'learner',iat,exp:iat+300});const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=Buffer.from(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(body))).toString('base64url');const token=body+'.'+sig;expect(await verifyRoomToken(token,secret,'one','https://schoolxense.ewinproject.org')).toBeTruthy();expect(await verifyRoomToken(token,secret,'two','https://schoolxense.ewinproject.org')).toBeNull();expect(await verifyRoomToken(token+'x',secret,'one','https://schoolxense.ewinproject.org')).toBeNull();expect(await verifyRoomToken(token,secret,'one','https://schoolxense.ewinproject.org',(iat+300)*1000)).toBeNull();});
 test('E-WIN link assertions are signed, short-lived and bound to their account subject',async()=>{const now=Date.now(),secret='link-test-secret',assertion:EwinLinkAssertion={version:1,platformId:'schoolcbt',platformSubject:'schoolxense:learner',centralUserId:'central-user',linkId:'central-link',referralCode:'EWIN-TEST',issuedAt:now,expiresAt:now+300_000};const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const signature=[...new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(JSON.stringify(assertion))))].map(x=>x.toString(16).padStart(2,'0')).join('');expect(await verifyEwinLink(assertion,signature,secret,now)).toBe(true);expect(await verifyEwinLink({...assertion,platformSubject:'schoolxense:other'},signature,secret,now)).toBe(false);expect(await verifyEwinLink(assertion,signature,secret,now+300_001)).toBe(false);expect(await verifyEwinLink(assertion,signature,undefined,now)).toBe(false);});
});
