import { describe, test, expect, vi, beforeEach, afterEach } from 'vitest';
import { convexTest } from 'convex-test';
import schema from '../../convex/schema';
import { api, internal } from '../../convex/_generated/api';
import { split } from '../../src/lib/engines/hiveShare';
vi.mock('../../convex/auth',()=>({authComponent:{safeGetAuthUser:async(ctx:any)=>{const i=await ctx.auth.getUserIdentity();return i?{_id:i.subject,emailVerified:i.emailVerified}:null;}}}));
vi.mock('../../convex/components',()=>({workflows:{start:vi.fn(async()=>{})}}));
const modules=import.meta.glob('../../convex/**/*.ts');
const identity=(subject:string)=>({subject,emailVerified:true});
async function fixture(minor=false){
 const t=convexTest(schema,modules);const ids=await t.run(async ctx=>{
  const add=async(name:string,isMinor=false)=>ctx.db.insert('users',{authId:name,name,email:`${name}@example.test`,isMinor,profileComplete:true,dailyMinutes:15,referralCode:name,creditsDays:0,streak:0,status:'active'});
  const owner=await add('owner'),learner=await add('learner',minor),tutor=await add('tutor'),other=await add('other'),parent=await add('parent');
  for(const [userId,role] of [[owner,'staff'],[learner,'learner'],[tutor,'tutor'],[parent,'guardian']] as const)await ctx.db.insert('roles',{userId,role,grantedAt:Date.now()});
  if(minor)await ctx.db.insert('guardianLinks',{guardianId:parent,childId:learner,spendingLimit:0n,createdAt:Date.now()});
  for(const kind of ['nin','safeguarding'] as const)await ctx.db.insert('verifications',{userId:tutor,kind,status:'approved'});
  const payment=await ctx.db.insert('payments',{userId:tutor,txRef:'tutor-plan',amount:200000n,currency:'NGN',purpose:'subscription',refId:`plus_month:${tutor}`,status:'successful',fulfilledAt:Date.now(),createdAt:Date.now()});
  const tutorSub=await ctx.db.insert('subscriptions',{userId:tutor,planId:'plus_month',paidBy:tutor,until:Date.now()+100*86400000,sourcePaymentId:payment,startedAt:Date.now()-1000});
  const offer=await ctx.db.insert('offers',{tutorId:tutor,title:'Physics support',subjects:['Physics'],topics:[],levels:[],languages:['English'],price:250000n,availability:[],module:'tutors',kind:'tutoring',active:true,minorsApproved:true,rating:0,reviews:0,completion:0,sessions:0});
  return {owner,learner,tutor,other,parent,offer,tutorSub};
 });
 const staff=t.withIdentity(identity('owner')),learner=t.withIdentity(identity('learner')),tutor=t.withIdentity(identity('tutor')),parent=t.withIdentity(identity('parent'));
 await staff.mutation(api.tutorBundles.configure,{enabled:true,sessionKobo:250000n});
 const slots=Array.from({length:12},(_,i)=>Date.now()+(i+2)*86400000);
 const roster=await tutor.mutation(api.tutorBundles.availability,{offerId:ids.offer,capacity:2,slots});await staff.mutation(api.tutorBundles.approveRoster,{id:roster,approved:true});
 const payer=minor?parent:learner;
 const order=await payer.mutation(api.checkout.order,{kind:'subscription',refId:'plus_tutor',...(minor?{beneficiaryId:ids.learner}:{})});
 await t.run(async ctx=>{await ctx.db.patch(order,{status:'successful',flwTxId:'verified-test-transaction'});for(let ordinal=1;ordinal<=6;ordinal++)await ctx.db.insert('escrows',{paymentId:order,refKind:'tutor_bundle',refId:`bundle:${order}:${ordinal}`,amount:250000n,currency:'NGN',status:'held',releaseAfter:Date.now()+90*86400000,split:split({kind:'session',grossKobo:250000}),recipients:{}});});
 await t.mutation(internal.money.afterPayment,{paymentId:order});const bundle=(await learner.query(api.tutorBundles.dashboard,{})).bundles[0];
 const preferences=async()=>learner.mutation(api.tutorBundles.preferences,{bundleId:bundle._id,subject:'Physics',goal:'Understand forces and solve original practice questions.'});
 const allocate=async()=>{await preferences();await staff.mutation(api.tutorBundles.allocate,{bundleId:bundle._id,offerId:ids.offer,note:'Verified physics tutor with safe availability.'});};
 return {t,ids,staff,learner,tutor,parent,payer,order,bundle,slots,roster,allocate};
}
beforeEach(()=>vi.useFakeTimers({toFake:['setTimeout','clearTimeout']}));
afterEach(()=>{vi.useRealTimers();vi.unstubAllEnvs();vi.restoreAllMocks();});
describe('Paid tutor bundle workflow',()=>{
 test('authoritative settlement reserves six funded shares and keeps the ledger balanced',async()=>{const f=await fixture();const order=await f.t.withIdentity(identity('other')).mutation(api.checkout.order,{kind:'subscription',refId:'plus_tutor'});const payment=await f.t.run(ctx=>ctx.db.get(order));await f.t.mutation(internal.money.settlePayment,{txRef:payment!.txRef,flwTxId:'provider-verified-second-order',amountKobo:2500000n,currency:'NGN'});const escrows=await f.t.run(ctx=>ctx.db.query('escrows').collect());expect(escrows.filter(x=>x.paymentId===order)).toHaveLength(6);expect(escrows.filter(x=>x.paymentId===order).reduce((n,x)=>n+x.amount,0n)).toBe(1500000n);const entries=await f.t.run(ctx=>ctx.db.query('ledgerEntries').collect());expect(entries.reduce((n,e)=>n+e.amount,0n)).toBe(0n);expect(entries.filter(e=>e.kind==='escrow').reduce((n,e)=>n+e.amount,0n)).toBe(1500000n);await f.t.mutation(internal.money.settlePayment,{txRef:payment!.txRef,flwTxId:'provider-verified-second-order',amountKobo:2500000n,currency:'NGN'});expect(await f.t.run(ctx=>ctx.db.query('ledgerEntries').collect())).toHaveLength(entries.length);await f.t.mutation(internal.money.afterPayment,{paymentId:order});expect((await f.t.withIdentity(identity('other')).query(api.tutorBundles.dashboard,{})).bundles[0].sessions).toHaveLength(6);});
 test('verified fulfilment creates exactly six credits and is idempotent',async()=>{const f=await fixture();expect(f.bundle.sessions).toHaveLength(6);expect(f.bundle.paid).toBe(true);await f.t.mutation(internal.money.afterPayment,{paymentId:f.order});expect(await f.t.run(ctx=>ctx.db.query('tutorBundles').collect())).toHaveLength(1);expect(await f.t.run(ctx=>ctx.db.query('tutorBundleSessions').collect())).toHaveLength(6);expect((await f.t.run(ctx=>ctx.db.get(f.order)))?.bundleSessionKobo).toBe(250000n);});
 test('anonymous, unrelated and unverified callers cannot inspect or change private records',async()=>{const f=await fixture();await expect(f.t.query(api.tutorBundles.dashboard,{})).rejects.toThrow('UNAUTHENTICATED');await expect(f.t.withIdentity(identity('other')).mutation(api.tutorBundles.preferences,{bundleId:f.bundle._id,subject:'Physics',goal:'Obtain someone else’s private tutoring.'})).rejects.toThrow('FORBIDDEN');await expect(f.learner.mutation(api.tutorBundles.configure,{enabled:true,sessionKobo:250000n})).rejects.toThrow('FORBIDDEN');expect((await f.t.withIdentity(identity('other')).query(api.tutorBundles.dashboard,{})).bundles).toHaveLength(0);});
 test('allocation requires preferences, approved identity, subject and capacity',async()=>{const f=await fixture();await expect(f.staff.mutation(api.tutorBundles.allocate,{bundleId:f.bundle._id,offerId:f.ids.offer,note:'Allocate verified subject tutor.'})).rejects.toThrow('Choose an approved tutor');await f.allocate();expect((await f.learner.query(api.tutorBundles.dashboard,{})).bundles[0].tutorId).toBe(f.ids.tutor);await f.t.run(ctx=>ctx.db.patch(f.ids.tutorSub,{until:Date.now()-1}));await expect(f.learner.mutation(api.tutorBundles.schedule,{sessionId:f.bundle.sessions[0]._id,startsAt:f.slots[0]})).rejects.toThrow('Select an available tutor');});
 test('guardian consent is enforced before a minor can schedule',async()=>{const f=await fixture(true);await f.allocate();await expect(f.learner.mutation(api.tutorBundles.schedule,{sessionId:f.bundle.sessions[0]._id,startsAt:f.slots[0]})).rejects.toThrow('ALLOCATION_AND_CONSENT_REQUIRED');await expect(f.learner.mutation(api.tutorBundles.consent,{bundleId:f.bundle._id})).rejects.toThrow('LINKED_GUARDIAN_REQUIRED');await f.parent.mutation(api.tutorBundles.consent,{bundleId:f.bundle._id});await f.parent.mutation(api.tutorBundles.schedule,{sessionId:f.bundle.sessions[0]._id,startsAt:f.slots[0]});const thread=await f.t.run(ctx=>ctx.db.query('threads').first());expect(thread?.guardianIncluded).toBe(true);expect(thread?.participants).toContain(f.ids.parent);});
 test('a reserved slot cannot consume two credits; cancellation restores the same credit',async()=>{const f=await fixture();await f.allocate();const first=f.bundle.sessions[0]._id;await f.learner.mutation(api.tutorBundles.schedule,{sessionId:first,startsAt:f.slots[0]});await expect(f.learner.mutation(api.tutorBundles.schedule,{sessionId:f.bundle.sessions[1]._id,startsAt:f.slots[0]})).rejects.toThrow('SLOT_ALREADY_RESERVED');await f.learner.mutation(api.tutorBundles.cancel,{sessionId:first});expect((await f.t.run(ctx=>ctx.db.get(first)))?.status).toBe('available');await f.learner.mutation(api.tutorBundles.schedule,{sessionId:first,startsAt:f.slots[1]});expect(await f.t.run(ctx=>ctx.db.query('tutorBundleSessions').collect())).toHaveLength(6);});
 test('expiry and refund block direct scheduling and cannot be bypassed by a saved role',async()=>{const f=await fixture();await f.allocate();await f.t.run(ctx=>ctx.db.patch(f.order,{status:'refunded'}));await expect(f.learner.mutation(api.tutorBundles.schedule,{sessionId:f.bundle.sessions[0]._id,startsAt:f.slots[0]})).rejects.toThrow('BUNDLE_PAYMENT_REQUIRED');await f.t.run(async ctx=>{await ctx.db.patch(f.order,{status:'successful'});await ctx.db.patch(f.bundle._id,{expiresAt:Date.now()-1});});await expect(f.learner.mutation(api.tutorBundles.schedule,{sessionId:f.bundle.sessions[0]._id,startsAt:f.slots[0]})).rejects.toThrow('BUNDLE_EXPIRED');});
 test('meeting URL stays private until the session window and unsafe URLs are rejected',async()=>{const f=await fixture();await f.allocate();const id=f.bundle.sessions[0]._id;await f.learner.mutation(api.tutorBundles.schedule,{sessionId:id,startsAt:f.slots[0]});await expect(f.tutor.mutation(api.tutorBundles.meeting,{sessionId:id,url:'https://untrusted.example/room'})).rejects.toThrow('secure Google Meet');await f.tutor.mutation(api.tutorBundles.meeting,{sessionId:id,url:'https://meet.google.com/abc-defg-hij'});expect((await f.learner.query(api.tutorBundles.dashboard,{})).bundles[0].sessions[0].meetingUrl).toBeUndefined();vi.spyOn(Date,'now').mockReturnValue(f.slots[0]-60000);expect((await f.learner.query(api.tutorBundles.dashboard,{})).bundles[0].sessions[0].meetingUrl).toContain('meet.google.com');});
 test('report requires delivery time and draft feedback before learner confirmation',async()=>{vi.useFakeTimers({toFake:['setTimeout','clearTimeout']});const f=await fixture();await f.allocate();const id=f.bundle.sessions[0]._id;await f.learner.mutation(api.tutorBundles.schedule,{sessionId:id,startsAt:f.slots[0]});await f.learner.mutation(api.tutorBundles.draft,{sessionId:id,draft:'My own explanation of how resultant force affects acceleration.',ownWork:true});const report={sessionId:id,covered:'Force and acceleration examples.',progress:'Learner solved two practice problems independently.',homework:'Retry three original problems tomorrow.',feedback:'Clarify the units and show the substitution steps.'};await expect(f.tutor.mutation(api.tutorBundles.report,report)).rejects.toThrow('after the 45-minute session');vi.spyOn(Date,'now').mockReturnValue(f.slots[0]+2700001);await f.tutor.mutation(api.tutorBundles.report,report);await expect(f.tutor.mutation(api.tutorBundles.confirm,{sessionId:id})).rejects.toThrow('LEARNER_CONFIRMATION_REQUIRED');await f.learner.mutation(api.tutorBundles.confirm,{sessionId:id});await expect(f.learner.mutation(api.tutorBundles.confirm,{sessionId:id})).rejects.toThrow('LEARNER_CONFIRMATION_REQUIRED');await f.t.finishAllScheduledFunctions(()=>vi.runAllTimers());const wallet=await f.tutor.query(api.money.myWallet,{});expect(wallet.available).toBe(200000n);const entries=await f.t.run(ctx=>ctx.db.query('ledgerEntries').collect());expect(entries.reduce((n,e)=>n+e.amount,0n)).toBe(0n);});
 test('disputes freeze the session share; independent staff can restore credit',async()=>{const f=await fixture();await f.allocate();const id=f.bundle.sessions[0]._id;await f.learner.mutation(api.tutorBundles.schedule,{sessionId:id,startsAt:f.slots[0]});await f.learner.mutation(api.tutorBundles.dispute,{sessionId:id,reason:'The tutor did not attend the agreed session.'});expect((await f.t.run(ctx=>ctx.db.query('escrows').first()))?.status).toBe('disputed');await expect(f.learner.mutation(api.tutorBundles.resolveDispute,{sessionId:id,decision:'restore_credit',note:'Reviewing the recorded no-show evidence.'})).rejects.toThrow('STAFF_REVIEW_REQUIRED');await f.staff.mutation(api.tutorBundles.resolveDispute,{sessionId:id,decision:'restore_credit',note:'No delivery evidence; return the original credit.'});expect((await f.t.run(ctx=>ctx.db.get(id)))?.status).toBe('available');expect((await f.tutor.query(api.money.myWallet,{})).available).toBe(0n);});
 test('compensation changes do not alter an existing paid allocation',async()=>{const f=await fixture();await f.allocate();await f.staff.mutation(api.tutorBundles.configure,{enabled:false,sessionKobo:200000n});await f.learner.mutation(api.tutorBundles.schedule,{sessionId:f.bundle.sessions[0]._id,startsAt:f.slots[0]});expect((await f.t.run(ctx=>ctx.db.get(f.bundle._id)))?.sessionKobo).toBe(250000n);await expect(f.t.withIdentity(identity('other')).mutation(api.checkout.order,{kind:'subscription',refId:'plus_tutor'})).rejects.toThrow('administrator activation');});
});
